### ISSUE TITLE
Redirect Help to correct page 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/aremi-natmap#101]
Currently, on the About landing page, the Help highlighted text directs users to wrong page (and generates 404 error message). 

Redirect Help hyperlink to correct page Help & FAQ. 

![image](https://cloud.githubusercontent.com/assets/18452161/26437830/c65f13bc-4162-11e7-9bbf-463ae7aa16ff.png)

![image](https://cloud.githubusercontent.com/assets/18452161/26437838/d43068b0-4162-11e7-9d29-d7b6975299a8.png)

**Comment by a-stacey** [comment]
Believe that this is the same as https://github.com/TerriaJS/aremi-natmap/issues/120 which has been fixed, please reopen if I am mistaken.
