### ISSUE TITLE
Add United Energy network constraints data

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/aremi-natmap#103]
In preparation for Energy workshops, add United Energy network constraints data https://www.unitedenergy.com.au/wp-content/uploads/2016/12/UE-Network-Limitations-Map-2016.zip

**Comment by AnaBelgun** [comment]
Data added on prototype but need to contact custodian to fix some issues:

It's a bit clunky up there right now for users due to the way kmz squishes the component layers together but nothing we can do without further engagement from United. 

Ideally we’d want United to help by:
1.	Creating legends
2.	Splitting out the data into component layers that can be uploaded separately

**Comment by axman6** [comment]
Asked to remove by ISF
