### ISSUE TITLE
Add new VIC data layers, under new catalogue structure

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/aremi-natmap#107]
These are to replace all the CSV files/data currently in AREMI under Victoria, Bioenergy (the data that currently exists under four folders: Aggregated by land use, Aggregated by LGA, Aggregated by Postcode and Aggregated by WRRG).
 
In addition to those listed in the attached, another 5-6 will be coming your way (MSW sector upload), but that will happen towards the end of the month.

[VIC ABBA layers Final V3_7Jun17.xlsx](https://github.com/TerriaJS/aremi-natmap/files/1056732/VIC.ABBA.layers.Final.V3_7Jun17.xlsx)

**Comment by AnaBelgun** [comment]
This issue takes priority over other VIC ABBA data issues:

**Comment by AnaBelgun** [comment]
ABBA confirmed they agree with the new VIC structure.

**Comment by AnaBelgun** [comment]
v5 data file
[VIC ABBA layers FINAL V5.xlsx](https://github.com/TerriaJS/aremi-natmap/files/1171499/VIC.ABBA.layers.FINAL.V5.xlsx)

**Comment by meh9** [comment]
Just updated with these changes from V5:

1. Added the 5 highlighted layers.
2. Removed the root level Livestock as it was missing in V5 and a copy of Agriculture->Livestock.
