### ISSUE TITLE
Add CER data 2012-2013 and 2013-2014

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/aremi-natmap#109]
- [ ] Add new CER NGERS designated facilities data for 2012-13 and 2013-14

- [ ] build a time series visualisation (TBC) 
[Copy of 20170606 - Publically avaliable data for AREMI (DGFs) 2012-13 - FINAL.xlsx](https://github.com/TerriaJS/aremi-natmap/files/1056900/Copy.of.20170606.-.Publically.avaliable.data.for.AREMI.DGFs.2012-13.-.FINAL.xlsx)
[Copy of 20170606 - Publically avaliable data for AREMI (DGFs) 2013-14 - FINAL.xlsx](https://github.com/TerriaJS/aremi-natmap/files/1056901/Copy.of.20170606.-.Publically.avaliable.data.for.AREMI.DGFs.2013-14.-.FINAL.xlsx)

**Comment by meh9** [comment]
AREMI is no more.
