### ISSUE TITLE
Add solar data with time series from solaranalytics.com.au

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/aremi-natmap#113]
User suggestion to upload voltage in different postcodes over time dataset
Referrer: https://nationalmap.gov.au/renewables/
Share URL: https://nationalmap.gov.au/renewables/#share=s-tsnOnROcXiJMBefP

**Comment by RachelBunder** [comment]
I just got it working: it looks like I had some malformed data that was causing the problem. Thanks for your time

Basically what I was trying to plot data that looks like:

postcode,date,voltage
2000,2017-01-01 00:00:00,240
2000,2017-01-01 00:05:00,239
....
2500,2017-01-01 00:00:00,245
2500,2017-01-01 00:05:00,237
etc.

**Comment by meh9** [comment]
@RachelBunder glad you got it working! :)
