### ISSUE TITLE
Add DNSP distribution districts layer

### ISSUE THREAD

**Issue by bje-** [TerriaJS/aremi-natmap#115]
It would be really useful to have an AREMI data set showing the coverage areas for the various DNSPs around Australia.  There are maps available of the distribution districts from the AER and other places. For example, here are the coverage maps for NSW and Victoria. Not sure what the definitive source of this spatial data is -- perhaps the AER?

http://www.resourcesandenergy.nsw.gov.au/__data/assets/pdf_file/0004/312637/NSW_DNSP_Distribution-Districts-map.pdf
http://www.smartmeters.vic.gov.au/__data/assets/image/0004/1175017/Figure-15-Boundaries-for-distribution-businesses-in-Victoria.jpg

**Comment by meh9** [comment]
It might be possible to make a view of this from the data for the Network Opportunity Maps. Will keep that in mind for the future.

**Comment by bje-** [comment]
Using the ISF Network Opportunities Map (eg Available Distribution Capacity), it is possible to click on a location and find out which network it belongs to. I think this is a more than sufficient solution, thanks!
