### ISSUE TITLE
Add scheduled loads from AEMO data

### ISSUE THREAD

**Issue by bje-** [TerriaJS/aremi-natmap#119]
There are a number of scheduled loads that could be suitably catalogued under "Electricity Infrastructure" -> "Scheduled loads", namely the DUIDs PUMP1, PUMP2 (Wivenhoe pumps) and SHPUMP (Shoalhaven pumps).  Does AREMI get scheduled loads in its feed?  I expect so, and it would be great to be able to superimpose these onto the corresponding generation data for those pumped hydro stations.

**Comment by bje-** [comment]
Note that Tumut 3's pumps are not classified as a scheduled load, but are identified by the DUID SNOWYP in the data.

**Comment by bje-** [comment]
Any interest in this one?

**Comment by meh9** [comment]
So, these are in the `Generation -> Current Power Generation -> All generation types` layer.

If I'm understanding correct I think that you are proposing a `Scheduled Loads` category alongside and separate to the `Generation` category?

That wouldn't be too hard to do. However, do you know if the current AEMO Dispatch SCADA data (http://nemweb.com.au/Reports/Current/Dispatch_SCADA/) include these as negative generation, or does that data come from a different source? If it's from a different source then it would be much more work.

**Comment by bje-** [comment]
Yes, having a Scheduled Loads category alongside and separate to the Generation category would be excellent. This would make it much easier to find and show the scheduled loads rather than treating them as a diffferent kind of generator.

I understand that these are "normally off" (hence 'norm off' in the descriptor). A positive value indicates that the load is on.  This is intuitive as it is and should remain consistent with the AEMO data.
