### ISSUE TITLE
CER data - baseline emissions for facilities

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/aremi-natmap#124]
The data is re. emissions baseline numbers set for facilities. At the moment the data is primarily the emissions baseline number – but commencing end February 2018, each of these facilities will be reporting their emissions annually, which will also be able to be published on AREMI. 
[AREMI website_Further information about the baseline dataset.docx](https://github.com/TerriaJS/aremi-natmap/files/1130067/AREMI.website_Further.information.about.the.baseline.dataset.docx)
[Copy of 20170706_Safeguard_facilities_for_AREMI_publication.xlsx](https://github.com/TerriaJS/aremi-natmap/files/1130068/Copy.of.20170706_Safeguard_facilities_for_AREMI_publication.xlsx)

**Comment by axman6** [comment]
Done
