### ISSUE TITLE
Add region to the AEMO generation data

### ISSUE THREAD

**Issue by meh9** [TerriaJS/aremi-natmap#125]
Since the NEM Region of a generator is in the AEMO input metadata we should display it.

Also check if there are other fields we are not showing. If so we should add them.

**Comment by bje-** [comment]
Note that Moree Solar Farm may be missing its NEM region (NSW1). It is missing in the NEM Registration and Exemption List spreadsheet (and I logged a problem report with AEMO).

**Comment by bje-** [comment]
The glitch in the NEM registration list has now (apparently) been fixed by AEMO, but is not yet showing up in the version of the AEMO website.

**Comment by axman6** [comment]
This is now in production, the region column has been added to the CSV on http://services.aremi.d61.io/aemo/v7/csv/all

@bje- Let us know how you go.

**Comment by bje-** [comment]
Thanks a lot!
