### ISSUE TITLE
Add new and update existing SA Bioenergy layers

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/aremi-natmap#129]
Original emails has all the hyperlinks. 

Below are the MapServer URL’s and layer URL’s. 

http://location.sa.gov.au/arcgis3/rest/services/AREMI
The new layers are in:
Add an Urban Waste folder for these three
AREMI/Municipal_Organic_Waste 
AREMI/Commercial_Industrial
          Legend
Built Up Areas (0)
COMMERCIAL & INDUSTRIAL SA4 (1)
AREMI/Construction_Demolition
Legend
Built Up Areas (0)
CONSTRUCTION & DEMOLITION SA4 (1)

Add a Forestry folder for these two
AREMI/Forestry_Residues – this isn’t working (see below)
Legend
FORESTRY RESIDUES - 2015 - 2019 (0)
FORESTRY RESIDUES - 2020 - 2024 (1)
FORESTRY RESIDUES - 2025 - 2029 (2)
FORESTRY RESIDUES - 2030 - 2034 (3)
FORESTRY RESIDUES - 2035 - 2039 (4)
FORESTRY RESIDUES - 2040 - 2044 (5)
FORESTRY RESIDUES - 2045 - 2049 (6)
FORESTRY RESIDUES - 2050 - 2054 (7)
FORESTRY RESIDUES - 2055 - 2059 (8)
FORESTRY RESIDUES - 2015 - 2059 (9)
SA NPI REGION BOUNDARIES (10)

AREMI/Green_Triangle_Biomass_Potential
Legend
GREEN TRIANGLE - BIOMASS POTENTIAL (0)
GREEN TRIANGLE - NPI REGION BOUNDARY (1)

Add to Agriculture
AREMI/Hay_Silage
Add to Horticulture
AREMI/Nursery_Flowers_Turf

AREMI/SE_Biomass 

Also the Green Triangle Forestry layer can now be removed.
http://location.sa.gov.au/arcgis3/rest/services/AREMI/Green_Triangle_Forestry/MapServer

I am getting an error when I try to load the Forestry Map Server manually whether I do it as individual layer URL’s or as that top MapServer URL.

**Comment by meh9** [comment]
Done.
