### ISSUE TITLE
Reported analysis tool error for the wave energy module

### ISSUE THREAD

**Issue by dbutrovski** [TerriaJS/aremi-natmap#130]
A user has reported an issue on morning 14 July 2017. The first part seems to be functionality/improvement request, the second is actual reported error.

I am trying to use the analysis tool in the wave energy module to extract time series data near Albany, WA. I am finding two issues: 
1. I cannot manually enter the specific coordinates I want, I can only select locations by clicking on the map
2. I am unable to actually generate any data with the analysis tool; no matter what analysis I try to do I get an error message simply saying "Request has failed"
Any help would be appreciated.

This is separate from the issue [https://github.com/TerriaJS/aremi-natmap/issues/112](url) that was closed on 10 July 2017.

Thanks,
Dmitar

**Comment by meh9** [comment]
With regards to the reported bug, I'm afraid I cannot reproduce it. I'm having no trouble making requests around Albany, WA. The following are all successful queries:

<img width="740" alt="screen shot 2017-07-18 at 11 34 03" src="https://user-images.githubusercontent.com/5283003/28296694-19179772-6bad-11e7-9b54-82b33530507b.png">

Please could you ask the user to try again, or perhaps give some more specific information about exact locations that failed and what browser they are using.

**Comment by dbutrovski** [comment]
User now believes the issue with accessing the analysis tool is specific to his computer or web browser as he was just able to do it on another computer. 

He asks whether there are specific settings within Google Chrome that need to be turned on or off for it to work? Is there any way I can ask the user to supply his browser configuration to you to have a look?

**Comment by meh9** [comment]
If using Google Chrome then the user can use the menu on the right, go to Help -> About Google Chrome, and tell us what version that says.

He may have extensions that are interfering with what is happening, or his organisations network configuration may be interfering with things.

In order to take things further I would then usually use the Dev Tools Network Tab to see what is actually happening with the analysis request. Something along these lines:

https://developers.google.com/web/tools/chrome-devtools/network-performance/issues

**Comment by axman6** [comment]
See #135 - AWAVEA have redirected their service to ours, but are redirecting to HTTPS, and their tools aren't using HTTPS.

**Comment by meh9** [comment]
I believe we have communicated with this user via email now, as has the AWAVEA team, and his issue is now solved. 

I have logged a separate issue for the request to be able to edit the lat/lon input field: #136
