### ISSUE TITLE
duplicate lines in AEMO power generation data

### ISSUE THREAD

**Issue by bje-** [TerriaJS/aremi-natmap#134]
The "all available" power generation data sets contain quite a large number of duplicate rows.  This throws out the counts, so you do not see, for example, 288 5-minute rows in every per day and complicates processing.  Can they be readily regenerated?

Here is an example using the BDL01 and BDL02 open cycle gas turbines.

$ wc -l BDL0?
  348229 BDL01
  348229 BDL02
  696458 total
$ for f in BDL0? ; do uniq -D $f | wc -l; done
1466
1466

**Comment by meh9** [comment]
We recently became aware of these duplicates. We have a fix that corrects the data (removes duplicates), but it's not clear why it has happened and are still investigating that.

**Comment by bje-** [comment]
Thanks. I have a workaround, of course, which is to run the data through uniq(1).
