### ISSUE TITLE
Incorrect dispatch type in generator data

### ISSUE THREAD

**Issue by bje-** [TerriaJS/aremi-natmap#138]
Select the "All generator types" data set and select the display variable "Dispatch type". This lists:

Generator
Load Norm Off
Network Service Provider
Generatir

Presumably the last one is a rogue value meant to be "Generator". Is this wrong in the AEMO data set?

**Comment by meh9** [comment]
Yes, looks like the RPCG generator has the wrong value entered by AEMO:

https://github.com/data61/aemo-archiver/blob/master/power_station_metadata/nem-Generators%20and%20Scheduled%20Loads.csv#L168

Please submit a bug report to AEMO to have that fixed.

**Comment by bje-** [comment]
Shall do!
