### ISSUE TITLE
some AEMO generation data missing

### ISSUE THREAD

**Issue by bje-** [TerriaJS/aremi-natmap#139]
I have observed some missing data in the generation traces, which surprises me.  For example, I downloaded the all-time data set for Capital Wind Farm. 14:15 is missing.

$ grep 2016-12-02T14 CAPTL_WF 
2016-12-02T14:00:00+0000,42.340
2016-12-02T14:05:00+0000,43.192
2016-12-02T14:10:00+0000,41.352
2016-12-02T14:20:00+0000,38.600
2016-12-02T14:25:00+0000,35.652
2016-12-02T14:30:00+0000,31.908
2016-12-02T14:35:00+0000,30.340
2016-12-02T14:40:00+0000,32.832
2016-12-02T14:45:00+0000,32.840
2016-12-02T14:50:00+0000,33.624
2016-12-02T14:55:00+0000,32.380

**Comment by bje-** [comment]
I take it this means that the upstream feed is missing values?  That surprises me somewhat.

**Comment by meh9** [comment]
So, I started having a look at this last week.

It's certainly possible that the upstream feed is missing a value - from memory we've seen a file go missing in the past. However I didn't immediately find the culprit, and other things got in the way so I've not managed to finish investigating yet.

**Comment by meh9** [comment]
However, bear in mind that these values are instantaneous generation as opposed to 5 minute average, so using them to count electrons is not really valid anyway, but I suppose that over a long enough time period the average of the values will be pretty close to the number of electrons.

**Comment by bje-** [comment]
I'm not using those values to count coulombs :-), I am treating them as instantaneous values as you describe.
