### ISSUE TITLE
AREMI v2017-07-25 pre-release test - Region names not recognised error

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/aremi-natmap#141]
Major 

- Catalogue group: Electricity Infrastructure/Residential/Household Energy Consumption 2010-2012

- The layers in the catalogue group generated 'Issues loading' error (see attached slides)

![slide1](https://user-images.githubusercontent.com/22827786/28696880-b3f4b3f8-737b-11e7-9cce-a49c7af792ed.JPG)
![slide2](https://user-images.githubusercontent.com/22827786/28696878-b3e3d330-737b-11e7-9fc3-8bf1f70e9030.JPG)
![slide3](https://user-images.githubusercontent.com/22827786/28696879-b3f310d4-737b-11e7-8cb8-d41c9a1f2d24.JPG)
![slide4](https://user-images.githubusercontent.com/22827786/28696881-b3f94030-737b-11e7-83e8-b4b4ba2c2ef0.JPG)

**Comment by meh9** [comment]
This is a problem in the data which is hosted separately. I'm working on getting that fixed right now.

**Comment by meh9** [comment]
The data has been updated to use the correct year release of the SA regions released by the ABS.

However, the data has been cached by the server for 24 hours, so unless we get the caches flushed this problem will remain until tomorrow at around 9:30am.

**Comment by meh9** [comment]
This has now been fixed.
