### ISSUE TITLE
Data Catalogue item Biogas Facilities produces error on data load in AREMI v2017-07-25

### ISSUE THREAD

**Issue by dbutrovski** [TerriaJS/aremi-natmap#143]
Error when trying to preview or add
[http://biogas.nceastg.usq.edu.au/data/biogas.csv](url)

> Unable to load CSV file
> See the csv-geo-au specification for supported CSV formats.
> undefined

**Comment by meh9** [comment]
Aha, I would guess that you are accessing AREMI over HTTPS? 

When you use HTTPS it doesn't allow mixed content, and it looks like I missed putting that host into the proxy whitelist.

**Comment by dbutrovski** [comment]
Yep, just confirmed. It works fine, i.e. I can preview and load the csv file, if not over HTTPS.

**Comment by meh9** [comment]
I've added it to the whitelist now for the next version.

**Comment by meh9** [comment]
Fixed in the next version.
