### ISSUE TITLE
Update Natural Resource Management Regions to use DoEE source

### ISSUE THREAD

**Issue by meh9** [TerriaJS/aremi-natmap#145]
AREMI is currently using the old NM Geoserver as the source of the NRM regions. The DoEE has since released their own version, we should use that to ensure we get updates etc.

Also check if there are other DoEE boundaries we should use in favour of the old NM server.

**Comment by meh9** [comment]
Use the list of the DoEE web services and look for the Natural Resource Management Regions layer: 

http://www.environment.gov.au/about-us/environmental-information-data/web-services

And if it looks good replace the AREMI one:

https://github.com/TerriaJS/aremi-natmap/blob/master/datasources/aremi/custodian/Australian_Bureau_of_Statistics/Boundaries.ejs#L87

**Comment by a-stacey** [comment]
The new layer differs substaintally from the old layer (old blue, new brown):
![screenshot from 2017-09-19 14-03-35](https://user-images.githubusercontent.com/4453477/30575609-6c0f9622-9d45-11e7-8019-6891622c67c4.png)

The new layer embeds license in access constraints (although doesn't specify version) and service contact:
![screenshot from 2017-09-19 14-11-50](https://user-images.githubusercontent.com/4453477/30575658-b815b2ae-9d45-11e7-9e5d-8d34f16e472d.png)

**Comment by a-stacey** [comment]
Was resolved in 8281cce.
