### ISSUE TITLE
more recent BoM solar data are available

### ISSUE THREAD

**Issue by bje-** [TerriaJS/aremi-natmap#146]
AREMI's DNI and GHI traces are available up to December 2015. According to BoM metadata, the dataset is now up to October 2016 and now includes observations from Himawari-8. Is it possible that the data set could be refreshed to include the partial 2016 year?

**Comment by meh9** [comment]
Unfortunately, there are no plans to update this dataset. It was made available as a static once-off reference for a long enough time period to be statistically useful only.

**Comment by bje-** [comment]
That's a pity, as it's the only sensible way of generating actual meteorological years for any location in Australia, and the most recent year is generally needed to match up with a realistic representation of current electricity demand.
