### ISSUE TITLE
AREMI 2017-07-25 pre-release test - Retest - Observation - Actual date in Chart

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/aremi-natmap#147]
**Observation**

Should the label 'date' in chart be the current date as the current times are showing of this date?

![slide1](https://user-images.githubusercontent.com/22827786/28908532-8c9484b4-7867-11e7-8388-b2b41de08dae.JPG)

**Comment by meh9** [comment]
Good observation, but in this case it's simply a label for the X-axis, saying that we are showing dates there. As you can see the Y-axis also has a label, in this case MW, so this is all as expected.
