### ISSUE TITLE
AREMI 2017-07-25 pre-release test - Retest updating of Chart in real time

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/aremi-natmap#148]
Layer: Electricity Infrastructure/Generation/Current Power Generation - NEM/All generation types

As requested by Data61 - an issue of Chart not being updated in real time has been tested.

A test performed on the latest fix loaded on 3 August 2017 at around 2.40 pm confirms that the Chart is being updated in real time for the data layer tested as expected.

![slide2](https://user-images.githubusercontent.com/22827786/28908776-bd5edfe4-7868-11e7-9f0d-9ba11b28e9d5.JPG)

![slide3](https://user-images.githubusercontent.com/22827786/28908779-c3c63008-7868-11e7-873d-9782503b74e8.JPG)

![slide4](https://user-images.githubusercontent.com/22827786/28908786-c996c510-7868-11e7-902b-32dabf8e6b9e.JPG)

**Comment by meh9** [comment]
Excellent news, thank you!
