### ISSUE TITLE
Update road/railways layers to be the same as NorthernAustralia map

### ISSUE THREAD

**Issue by meh9** [TerriaJS/aremi-natmap#149]
The NorthernAustralia map is using better road/rail layers from GA, we should switch to them.

**Comment by meh9** [comment]
@a-stacey: Have a look at the NorthernAustralia Road and Rail layers:

https://github.com/TerriaJS/NorthernAustralia/blob/master/wwwroot/init/nainvest.json#L96

And update the AREMI ones:

https://github.com/TerriaJS/aremi-natmap/blob/master/datasources/aremi/custodian/Geoscience_Australia/Transport_layers.ejs#L37

**Comment by a-stacey** [comment]
Should I be preserving the ids from the existing layers?

Also I have preserved the initial message and layer names from the NorthernAustralia map, not sure if the road should just be listed as "Road" on AREMI.

Also have added `<% include ../../common/standard_properties %>`...but had trouble adding `<% include ../../common/home_camera_rectangle %>`, not sure if this is important or what the impact of this is.

**Comment by meh9** [comment]
Yes, please preserve the id's - this is how share links don't break when we update layers.

**Comment by meh9** [comment]
Did you have trouble with the home_camera because it requires the previous line to end with a comma?

**Comment by meh9** [comment]
I think ditch the initialMessage and you should also be able to ditch the License because that should be already in the service now, might have to just try it.

**Comment by a-stacey** [comment]
> Did you have trouble with the home_camera because it requires the previous line to end with a comma?
I thought I'd done this, but when retested now it worked...might have been doing something dumb like using a semicolon instead of a comma...

> I think ditch the initialMessage and you should also be able to ditch the License because that should be already in the service now, might have to just try it.
Have removed the initialMessage but retained the License as it does not show otherwise. This appears to be the dataset on data.gov.au showing that this is the current license in effect: https://data.gov.au/dataset/dynamic-national-map-transport-infrastructure-wms

**Comment by a-stacey** [comment]
Was resolved in c6310c9.
