### ISSUE TITLE
Aspect/Slope layers have changed service endpoint

### ISSUE THREAD

**Issue by meh9** [TerriaJS/aremi-natmap#152]
The following datasets have been decommissioned:
 
http://www.ga.gov.au/gisimg/services/topography/dem_s_slopepct/ImageServer/WMSServer
 
and replaced with
 
http://services.ga.gov.au/gis/rest/services/DEM_SRTM_1Second_Aspect/MapServer and http://services.ga.gov.au/gis/rest/services/DEM_SRTM_1Second_Slope/MapServer

**Comment by meh9** [comment]
@a-stacey:

```
$ grep -r dem_s_slopepct datasources/aremi/custodian/Geoscience_Australia
```

and replace the two hits with the new URL's, render the new catalogue, and test that the new services work.

**Comment by a-stacey** [comment]
Have implemented as follows with out legend:
![screenshot from 2017-09-19 10-37-00](https://user-images.githubusercontent.com/4453477/30570826-1295e1f0-9d27-11e7-905e-4cfa911ad231.png)

Legend options include:
![screenshot from 2017-09-19 10-39-10](https://user-images.githubusercontent.com/4453477/30570839-29ee1f34-9d27-11e7-8552-12247a1bff9e.png)
(the following with or with out the green / pink gridlines)
![screenshot from 2017-09-19 10-38-21](https://user-images.githubusercontent.com/4453477/30570840-29ef4aee-9d27-11e7-9b79-ffe7a7b32fa5.png)
but neither seemed to add any useful information to me.

As for slope it seems that this layer might be broken, as it only seems to highlight waterbodies:
http://services.ga.gov.au/site_13/rest/services/DEM_SRTM_1Second_Slope/MapServer?f=jsapi
![screenshot from 2017-09-19 10-40-19](https://user-images.githubusercontent.com/4453477/30570871-4ea21c04-9d27-11e7-9aa4-3edc5b27835b.png)

**Comment by meh9** [comment]
Right choice made on legend and what to show I think.

We'll have to get back to GA re broken Slope layer.

**Comment by meh9** [comment]
I have removed the broken Slope layer.
