### ISSUE TITLE
RIRDC's website has changed, and the Biomass People & Projects layers are broken

### ISSUE THREAD

**Issue by axman6** [TerriaJS/aremi-natmap#155]
Looks like RIRDC have got a new website, and it's broken things.

Relevant URLS:
- http://www.agrifutures.com.au/docs/default-document-library/biomass-producer-data-csv-format-for-aremi-upload-projects.csv
- http://www.rirdc.gov.au/docs/default-document-library/biomass-producer-data-csv-format-for-aremi-upload-projects.csv
- http://www.rirdc.gov.au/docs/default-document-library/biomass-producer-data-csv-format-for-aremi-upload-case-studies.csv

**Comment by meh9** [comment]
@axman6 see if you can find out from the metadata we have who is responsible for them, send them an email CC me, and then remove them from this release.

**Comment by axman6** [comment]
Have emailed Julie to follow up
