### ISSUE TITLE
New NSW forestry layers

### ISSUE THREAD

**Issue by meh9** [TerriaJS/aremi-natmap#162]
Place them all under the Forestry folder and drop the Forestry word from the name (as we did with the previous harvest residue layers). They all contain one layer, so no need to be in additional folders, they can just go under the Forestry folder heading with the layer names below suggested in italics.

Forestry folder

Harvest Residues - Public Forests Overview
https://spatial.industry.nsw.gov.au/arcgis/rest/services/Bioenergy_Assessment/Forestry_Harvest_Residues_Public_Forests_Overview/MapServer

Harvest Residues - Public Native Forests
https://spatial.industry.nsw.gov.au/arcgis/rest/services/Bioenergy_Assessment/Forestry_Harvest_Residues_Public_Native_Forests/MapServer

Harvest Residues - Public Plantation Hardwood
https://spatial.industry.nsw.gov.au/arcgis/rest/services/Bioenergy_Assessment/Forestry_Harvest_Residues_Public_Plantation_Hardwood/MapServer

Harvest Residues - Public Plantation Softwood
https://spatial.industry.nsw.gov.au/arcgis/rest/services/Bioenergy_Assessment/Forestry_Harvest_Residues_Public_Plantation_Softwood/MapServer

This is how we did the previous ones, just drop the new ones in at the bottom without being in any of the subgroups:

https://github.com/TerriaJS/aremi-natmap/blob/master/datasources/aremi/custodian/NSW_Department_of_Primary_Industries/Forestry.ejs

Should be able to just copy and paste one of the existing ones and change the `id`, `url`, and `layers`.

**Comment by a-stacey** [comment]
![screenshot from 2017-09-19 16-54-02](https://user-images.githubusercontent.com/4453477/30579405-ea1801d8-9d5b-11e7-8f6a-d12e46720c14.png)
