### ISSUE TITLE
AREMI v2017-09-22 pre-release test - Available Distribution Capacity - Error

### ISSUE THREAD

**Issue by TheAngeloPace** [TerriaJS/aremi-natmap#167]
Major Issue:

Error loading 'Available Distribution Capacity' data layer issue with region names.

![slide1](https://user-images.githubusercontent.com/20634718/30944881-300ef9ce-a43e-11e7-8ab5-3b0d9188d08e.JPG)
#

**Comment by axman6** [comment]
Hi Angelo,

I believe this is because ISF are in the process of updating this data. We've been told it will be ready by the time of the release, but if it is not, will will be updated by the custodian at some point soon after and these problems will disappear.

**Comment by meh9** [comment]
This has now been fixed by the data custodian.
