### ISSUE TITLE
AREMI v2017-09-22 pre-release test - Annual Deferral Value - Error

### ISSUE THREAD

**Issue by TheAngeloPace** [TerriaJS/aremi-natmap#168]
Major Issue:

Error loading 'Annual Deferral Value' data layer issue with region names.

![slide2](https://user-images.githubusercontent.com/20634718/30944971-d04db2c2-a43e-11e7-8e96-53485d93eb0b.JPG)

**Comment by meh9** [comment]
This is not a major issue.

It is a notice that there are regions in the data not available in the region map, and these can therefore not be displayed. However, for the regions that exist the data is shown.

The data custodian is aware and they are working on resolving the issue.

**Comment by meh9** [comment]
This has now been fixed by the data custodian.
