### ISSUE TITLE
AREMI v2017-09-22 pre-release test - Unable to load CSV - Error

### ISSUE THREAD

**Issue by TheAngeloPace** [TerriaJS/aremi-natmap#170]
Major Issue:

- Unable to load data published on site.

![slide8](https://user-images.githubusercontent.com/20634718/30945178-05c65016-a440-11e7-9180-ab37e9acf6a7.JPG)

**Comment by meh9** [comment]
Aha, it looks like a host got dropped from the white list. I've added it back.

**Comment by TheAngeloPace** [comment]
Have checked this morning and this issue is still present.

**Comment by meh9** [comment]
That is correct, I should have said that I have fixed it in the source, but it will take a new release to fix it in production.
