### ISSUE TITLE
AREMI v2017-09-22 pre-release test - Long Delays - Observation

### ISSUE THREAD

**Issue by TheAngeloPace** [TerriaJS/aremi-natmap#171]
Observation only:

It took approximately 5 minutes for the request to be completed and presented.

![slide9](https://user-images.githubusercontent.com/20634718/30945237-7f9f03ba-a440-11e7-9098-08afb24f395f.JPG)

![slide10](https://user-images.githubusercontent.com/20634718/30945243-85767e30-a440-11e7-8c9b-aa62ccac1ab4.JPG)

**Comment by meh9** [comment]
Thanks. We will speak to the data custodian to try to get them to make loading this data faster.

**Comment by meh9** [comment]
This service seems to work much faster now.
