### ISSUE TITLE
AREMI v2017-09-22 pre-release test - Land slope in percentage data - Error

### ISSUE THREAD

**Issue by TheAngeloPace** [TerriaJS/aremi-natmap#172]
Major Issue:

- Unable to load data published on site.

![slide11](https://user-images.githubusercontent.com/20634718/30945302-dfa84474-a440-11e7-83d0-77a6f2b59eeb.JPG)

**Comment by meh9** [comment]
This layer has now been removed as we work with Geoscience Australia to use a new service.
