### ISSUE TITLE
AREMI v2017-09-22 pre-release test - GetCodeListValue on ABS ITT - Error

### ISSUE THREAD

**Issue by TheAngeloPace** [TerriaJS/aremi-natmap#173]
Major Issue:

- Unable to load data published on site.

![slide12](https://user-images.githubusercontent.com/20634718/30945348-26985266-a441-11e7-8db8-5e1e0aa1e8c0.JPG)

**Comment by meh9** [comment]
This is now working, the data custodian must have fixed their issue.
