### ISSUE TITLE
HTTP error 504 fetching aemo/v7/csv/all

### ISSUE THREAD

**Issue by bje-** [TerriaJS/aremi-natmap#175]
Quite regularly, accessing `http://services.aremi.d61.io/aemo/v7/csv/all` I get HTTP response 504 (gateway timeout). Is this easy to fix or should my script just be more robust? ;-)

**Comment by meh9** [comment]
Yes, this shouldn't happen. We'll look into it and may work with you in case we have problems reproducing the issue?

**Comment by bje-** [comment]
I am reasonably satisfied that this is fixed. If the problem re-emerges, I will open a new issue. Thanks.
