### ISSUE TITLE
Error when adding Broadband ADSL Quality and Broadband Availability and Quality layers

### ISSUE THREAD

**Issue by dbutrovski** [TerriaJS/aremi-natmap#176]
User reported error, confirmed issue. When trying to add Broadband ADSL Quality and Broadband Availability and Quality the following error message appears:

An error occurred
AREMI experienced an error. Please report this by emailing
aremi@ga.gov.au. Details of the error are below.
Request has failed. Status Code: 500

User also mentioned that he would also like to make use of the WMS and WFS services for the broadband datasets mentioned above but it appears that the services do not support Cross-Origin Resource Sharing (CORS).

**Comment by AnaBelgun** [comment]
@meh9 @axman6  These layers are currently working in NationalMap.

**Comment by meh9** [comment]
This has been fixed and will be included in the next version.
