### ISSUE TITLE
WA Western Power data changes on AREMI

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/aremi-natmap#177]
The following changes need to be implemented on AREMI, ideally included in the Nov 17 release. 

Landgate/SLIP team advice: 
Western Power have re-released their data on our new SLIP platform. The old SLIP platform that you’re using is due to be decommissioned in Q1 2018, so this is an ideal time to migrate AREMI across to the new services.

You can find the new (31 data) links to Western Power’s services by browsing their organisation on data.wa.gov.au - https://catalogue.data.wa.gov.au/organization/western-power 

The dataset names have changed slightly, but you can use the WP-XXXX identifiers to find the datasets you’re using. e.g. The “Distribution Lines (WP-003)” dataset is now called “NCMT WP High Voltage Distribution Lines (WP-003)”.

Western Power’s data still requires you to register a free account to access it – you can find instructions for doing so at https://toolkit.data.wa.gov.au/hc/en-gb/articles/115009696588-How-do-I-create-an-account-with-SLIP-to-access-geospatial-data-.

Licence conditions: https://catalogue.data.wa.gov.au/dataset/34741550-f3d1-4910-adb1-9dac862670c7/resource/5c0d580f-85a6-42de-ab47-036e70bcd2ad/download/slip-licence-conditions.pdf

**Comment by meh9** [comment]
Done.
