### ISSUE TITLE
Add ABBA WA data layers

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/aremi-natmap#182]
- [x] Broiler poultry layer -  some problems getting it display on an LGA basis. The link to the data is below and the metadata is attached. Please display the capacity, number of properties and total residue layers please and the rest can be shapefile attributes: https://catalogue.data.wa.gov.au/dataset/96510712-c7a5-42d7-b253-a2118769ec03/resource/f9b5d927-72d5-41cc-808f-0a99a44e1ba
Metadata file:
[Broiler-metadata101117.docx](https://github.com/TerriaJS/aremi-natmap/files/1445048/Broiler-metadata101117.docx)

- [x] Dairy layer -  display the Dairy cattle, Total Residues and Number of properties fields please. The rest can be attributes of the shapefile. The link is, https://catalogue.data.wa.gov.au/dataset/f6fccc74-bcee-4b9e-9923-b6d9fd690baf/resource/c1af3f11-d386-4de7-a09c-81cf19acdc5a
Metadata file: 
[Dairy metadata.docx](https://github.com/TerriaJS/aremi-natmap/files/1445050/Dairy.metadata.docx)

- [x] Feedlot data - Please display only 3 columns: the Manure WTW, Manure dry Weight and Seasonality. The rest can be attributes. The link is, https://catalogue.data.wa.gov.au/dataset/d9c54d3a-854e-40d8-8cc6-f77f3ce8a135/resource/dcc2e333-cfd4-4575-9d17-65cffe30b22
Metadata file: 
[Cattle feedlot metadata.docx](https://github.com/TerriaJS/aremi-natmap/files/1445056/Cattle.feedlot.metadata.docx)

- [x] Check why this data by LGA doesn't work on AREMI 
[Copy of Broilers-DPIRD311017.xlsx](https://github.com/TerriaJS/aremi-natmap/files/1445059/Copy.of.Broilers-DPIRD311017.xlsx)

**Comment by meh9** [comment]
All done.

**Comment by AnaBelgun** [comment]
S'more (through https://data.wa.gov.au/): 

- [ ] Mechanical Harvested Vegetable Residue Layer to be Uploaded to AREMI: 1st Columns is the region differentiation sa2_name_2016 and we would like the next two columns to be displayed as variables that can be mapped and the remaining columns hidden 
 
URL for downloadable  csv file is
https://catalogue.data.wa.gov.au/dataset/639aba48-3413-49a5-a5c9-0964750ea355/resource/f040c69b-1d6d-4ac4-8822-5c34d6c0ffb8/download/estimated-vegies-mech-harvest-residue.csv

Metadata: 
[Mech Harvested Vege Residue Metadata.docx](https://github.com/TerriaJS/aremi-natmap/files/1448223/Mech.Harvested.Vege.Residue.Metadata.docx)

**Comment by meh9** [comment]
Done.

**Comment by AnaBelgun** [comment]
- [ ] Avocado data:
For the above layer 1st Columns is the region differentiation sa2_name_2016 and we would like the next three columns to be displayed as variables that can be mapped and the remaining columns hidden please.
URL: catalogue.data.wa.gov.au/dataset/avocado-residue

- [ ] Stone fruit
For the above layer 1st Columns is the region differentiation sa2_name_2016 and we would like the next three columns to be displayed as variables that can be mapped and the remaining columns hidden.
URL: catalogue.data.wa.gov.au/dataset/stone-fruit-residue

- [ ] Pomme fruit
For the above layer 1st Columns is the region differentiation sa2_name_2016 and we would like the next two columns to be displayed as variables that can be mapped and the remaining columns hidden please.
URL: catalogue.data.wa.gov.au/dataset/pome-fruit-residue

- [ ] Citrus 
For the above layer 1st Columns is the region differentiation sa2_name_2016 and we would like the next two columns to be displayed as variables that can be mapped and the remaining columns hidden 
URL: catalogue.data.wa.gov.au/dataset/citrus-fruit-residue

**Comment by meh9** [comment]
It's all done. :)
