### ISSUE TITLE
Add SA data 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/aremi-natmap#183]
Here is the Piggery Residues data.

https://location.sa.gov.au/arcgis3/rest/services/AREMI/National_Piggery_Residues/MapServer

There are two layers in this folder.
https://location.sa.gov.au/arcgis3/rest/services/AREMI/National_Piggery_Residues/MapServer/0
https://location.sa.gov.au/arcgis3/rest/services/AREMI/National_Piggery_Residues/MapServer/1

This is a National Layer. 

I will have some additional Winery data to upload as well.  What is the latest I can send this to you – I am aiming for the end of the week.

**Comment by meh9** [comment]
Done.

**Comment by AnaBelgun** [comment]
And some winery data updates: 

Here is a data upload that goes with the winery residues data.
http://location.sa.gov.au/arcgis3/rest/services/AREMI/National_Winery_Residues_Processing_Facilities/MapServer

Containing the following two data layers:
http://location.sa.gov.au/arcgis3/rest/services/AREMI/National_Winery_Residues_Processing_Facilities/MapServer/0
http://location.sa.gov.au/arcgis3/rest/services/AREMI/National_Winery_Residues_Processing_Facilities/MapServer/1

**Comment by meh9** [comment]
Done.
