### ISSUE TITLE
Enable HTTPS on AREMI `services` and `gis` services

### ISSUE THREAD

**Issue by meh9** [TerriaJS/aremi-natmap#184]
At the moment AREMI systems are only available using HTTP connections. We should make these available using HTTPS in order to avoid mixed-content failures when accessing them from a HTTPS context, as well as being good internet citizens.

**Comment by axman6** [comment]
All done, the aremi-stacks repo has been updated so all services support https in production production, and commit 390953db8ed3409a96ae7ad9396da4586f81691f makes these services use https by default.
