### ISSUE TITLE
AREMI v2017-11-13 pre-release test - Error loading layer - 1

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/aremi-natmap#186]
Error loading data layer

Layer: Renewable Energy/Bioenergy/National/Winery Residues

![slide1](https://user-images.githubusercontent.com/22827786/32763305-019c98dc-c953-11e7-9003-1a8224129257.JPG)

**Comment by meh9** [comment]
Thanks - the data custodian has said that they think they will have the data back up by the time it goes into production.

**Comment by meh9** [comment]
This layer has been removed from the most recent release.
