### ISSUE TITLE
AREMI v2017-11-13 pre-release test - Observation - Missing legend, Feature Info

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/aremi-natmap#188]
**Observation**

The data displayed by the layer is meaningless to the user as there is no Legend nor the user can click to get any feature info!

Layer: Research/NICTA Geothermal Model/Big Lake granite probability, 5.4km

![slide6](https://user-images.githubusercontent.com/22827786/32818269-45087d2a-ca16-11e7-9d94-813ce8b35207.JPG)

![slide5](https://user-images.githubusercontent.com/22827786/32818275-50b7310c-ca16-11e7-8da7-4fb032bc4084.JPG)

**Comment by meh9** [comment]
Thanks.

These are old and rarely used, so I've removed them from the next release.

Closed in https://github.com/TerriaJS/aremi-natmap/commit/8d2bc3055c54592f75a1e3bc3995a17271a087f5
