### ISSUE TITLE
AREMI v2018-01-24 pre-release test - Wave Model and Context Layers throws errors

### ISSUE THREAD

**Issue by jimmyjamesga** [TerriaJS/aremi-natmap#193]
The Folder Renewable energy> Wave > Wave Model and Context Layers Throws the below error when we try to open the Folder

![image001](https://user-images.githubusercontent.com/35437484/35488362-8c3e406c-04db-11e8-9fd7-ab8027e92d53.jpg)

**Comment by AnaBelgun** [comment]
Wave Atlas service url has changed;  this issue will address it: https://github.com/TerriaJS/aremi-natmap/issues/198
