### ISSUE TITLE
AREMI v2018-01-24 pre-release test - Analysis tools not showing data

### ISSUE THREAD

**Issue by jimmyjamesga** [TerriaJS/aremi-natmap#194]
Select any of the links of Renewable energy> Wave > Analysis Tools and click 'run Analysis'.

The below error is displayed

![image002](https://user-images.githubusercontent.com/35437484/35488376-ecbc4826-04db-11e8-9ab3-f23833dee33b.jpg)

If you select the Required fields and try to display them the below error occurs

![image003](https://user-images.githubusercontent.com/35437484/35488379-f5e254c2-04db-11e8-9501-1eae97807241.jpg)

The info Panel error is below
![image004](https://user-images.githubusercontent.com/35437484/35488381-fdeb975a-04db-11e8-91df-be35d597306e.jpg)

**Comment by AnaBelgun** [comment]
Wave Atlas service url has changed;  this issue will address it: https://github.com/TerriaJS/aremi-natmap/issues/198
