### ISSUE TITLE
AREMI v2018-01-24 pre-release test - Sawdust and Shavings link returns errors

### ISSUE THREAD

**Issue by jimmyjamesga** [TerriaJS/aremi-natmap#195]
The Renewable Energy >Bioenergy > Victoria > Forestry > Wood Processing Residues>Plantation Softwood >Sawdust and Shavings link returns errors:

![image006](https://user-images.githubusercontent.com/35437484/35488390-3cee8214-04dc-11e8-92ee-5ec416f6b94c.jpg)

**Comment by meh9** [comment]
This is an issue where the data for the layer has two regions with the same id. We have notified the data custodian asking them to fix the issue.

The impact is low, as it means that one region (which in this case looks like the one with the incorrect id) is not being displayed.

**Comment by meh9** [comment]
This has now been fixed.
