### ISSUE TITLE
AREMI v2018-01-24 pre-release test - River Regions Returning Missing Data

### ISSUE THREAD

**Issue by jimmyjamesga** [TerriaJS/aremi-natmap#196]
the Link at Renewable Energy> Hydro>River Regions Returns a missing data error

![image007](https://user-images.githubusercontent.com/35437484/35488398-68800704-04dc-11e8-8b61-d90fc4b4abbd.jpg)

On testing the actual link (below) that returns the data it returns a 200 response
http://services.ga.gov.au/gis/rest/services/Surface_Hydrology_WM/MapServer

The same Issue can be seen in Topography > Water > River Regions as well

**Comment by meh9** [comment]
Removed the layer.

**Comment by jimmyjamesga** [comment]
There are 2 layers that have River Regions. 
Topography > Water > River Regions Has not been Removed
