### ISSUE TITLE
AREMI v2018-01-24 pre-release test - Australian Bureau of Statistics errors

### ISSUE THREAD

**Issue by jimmyjamesga** [TerriaJS/aremi-natmap#197]
The Below linke in the Population > Australian Bureau of Statistics> return an unexpected format error

B32 Tenure Type and Landlord Type by Dwelling Structure
B33 Mortgage Repayment (monthly) by Dwelling Structure
B35 Type of Internet Connection by Dwelling Structure

![image009](https://user-images.githubusercontent.com/35437484/35488414-a8146ed2-04dc-11e8-9193-47c4cf7a11ca.jpg)

**Comment by meh9** [comment]
Removed the faulty layers.
