### ISSUE TITLE
AREMI v2018-01-30b pre-release test - Error running the Analysis Tools

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/aremi-natmap#199]
**Error running the Analysis Tools**

- Analysis Tools (Slide 1) generating error (Slide 2)
- This issue has been reported in last test run (Slide 3)

![slide1](https://user-images.githubusercontent.com/22827786/36514777-1a353890-176e-11e8-898d-159f7607efb6.JPG)

![slide2](https://user-images.githubusercontent.com/22827786/36514780-1eb6bec0-176e-11e8-8ef5-f96cd641aa76.JPG)

![slide3](https://user-images.githubusercontent.com/22827786/36514788-22e2086a-176e-11e8-8f26-f7b1f871096f.JPG)

**Comment by meh9** [comment]
Wave Atlas Analysis Tools are working again - unfortunately the data custodian has occasional issues with their infrastructure it seems.
