### ISSUE TITLE
AREMI v2018-01-30b pre-release test - Observation - Test ArcGIS Token access for two GA Cadastral boundary layers

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/aremi-natmap#200]
ArcGIS Token support for the two layers "Boundaries -> Cadastre and Land Tenure -> {Cadastral Parcels,Land Tenure}", as requested by Geoscience Australia.

Tested successfully

![slide4](https://user-images.githubusercontent.com/22827786/36514841-8ffe5548-176e-11e8-909a-8afd211ce03b.JPG)

**Comment by meh9** [comment]
Great! :D
