### ISSUE TITLE
Add ABBA VIC new layers and metadata

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/aremi-natmap#207]
Few things for this release: 

- [x] change Paper and Cardboard name into Branch

- [x] make changes to catalogue according to spreadsheet (revised version 22-03-2018)
[All Cover Pages Upload 4 220318.xlsx](https://github.com/TerriaJS/aremi-natmap/files/1823470/All.Cover.Pages.Upload.4.220318.xlsx)

- [x] add Waste Water Treatment Plants (according to new spreadsheet)

**Comment by meh9** [comment]
Done.
