### ISSUE TITLE
Add ANU STORES - v1 data 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/aremi-natmap#208]
- [ ] Add ANU STORES pumped hydro v1

**Comment by AnaBelgun** [comment]
- [ ] confirm with ARENA

**Comment by AnaBelgun** [comment]
Note text on the disclaimer to be updated. 
To delete: NOTE: The visualisation of the ANU STORES data on AREMI is still in development - _it is not part of the AREMI data catalogue yet._

**Comment by meh9** [comment]
This layer has been added and is now available on the prototype.
