### ISSUE TITLE
Replace All power stations (GA - 2014) with newest data (2017)

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/aremi-natmap#210]
All power stations data from GA is dated 2014. 
It has been updated on data.gov.au with 2017 version, but as a csv and KMZ, not a WMS. 
Given that data on AREMI is too old, we could replace it with the csv/kmz if possible: https://data.gov.au/dataset/power-stations

**Comment by AnaBelgun** [comment]
When asked about availability of the new service, GA said it will take some time, because they are restructuring their current ones.

**Comment by axman6** [comment]
We've received no response from GA on the issues with this dataset (raised on the 15th or March) so won't be able to include it in this release - if the dataset were included and then the issues fixed they would likely break the release.
