### ISSUE TITLE
ABBA QLD - Investigate best csv (option)

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/aremi-natmap#212]
The Queensland ABBA team have been updating our data and grouping it to a LGA levle so that we can publish this data as CSVs instead of WMS. We are finding that people are asking for this data at this LGA level and it will be easier for people to access and easier for us to maintain into the future. 

We will eventually get you delete the WMSs that we have already link to AREMI and replace this with a link to the CSVs that we publish on our open data portal - but this won’t be for at least a few weeks. But for now I am just pulling all of our data together so that this can be done all at once. 

One data set which is giving me grief however is our data on Urban Waste.  

I have two options for displaying this data in a CSV – one which I prefer but I’m not sure will work with AREMI. 

I have attached the two ways that we can display our data. I would prefer to use the URBANWASTE_2 csv as this will allow us to better display the same data on a dashboard that we are creating for a state government website. However when I drop this into ARMEI it only shows the first set of LGA data (even though the total residue is displaying all of the total – for each of the component of urban waste – food, paper, timber, green, grease trap and other). 

Can you let me know if there is a way that I can display the data from the CSV URBANWATSE_2 so that it will show the separate category for waste (in the column RESIDUE TYPE (food, paper etc) but for the one LGA only? This is achieved by displaying the data in URBANWASTE_1 but I would prefer not to have to do it this way. 

Otherwise we may end up having 6 different CSV for displaying each component of urban waste (food, paper, green, timber, grease trap and other). 

If this does not make sense please let me know. 

https://docs.google.com/spreadsheets/d/1a8JNC0_-DquQmi3nKqsed4fnUmc26GxhYcoT3i51XHU/edit?usp=drive_web&ouid=117266041899516419115

https://docs.google.com/spreadsheets/d/1rXN59LjYWGMzVwGKwJZfOHGMJVNkrZTKrgsx91r70Vs/edit?usp=drive_web&ouid=117266041899516419115

**Comment by meh9** [comment]
Investigated. Unfortunately Terria only supports the _1 format.
