### ISSUE TITLE
AREMI v2018-03-26 pre-release test - Observation - Zoom to Extent missing in whole group

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/aremi-natmap#213]
Updated "Renewable Energy/Bioenergy/Victoria" layers missing the 'Zoom to Extent' function!!

![slide1](https://user-images.githubusercontent.com/22827786/38070027-5d5c5690-3365-11e8-800d-067dd823166a.JPG)

**Comment by meh9** [comment]
Noted, we will fix this for the next release.

**Comment by meh9** [comment]
Extents have been added.
