### ISSUE TITLE
AREMI v2018-03-26 pre-release test - Observation - Layer fail on 1st attempt but works fine on second

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/aremi-natmap#215]
This is confusing, generates error on 1st attempt but works fine on later attempts!!

For example:
Layer: Renewable Energy/Bioenergy/Victoria/Horticulture/Fruit and vegetable/Cull fruit
Layer: Renewable Energy/Bioenergy/Victoria/Municipal Solid Waste/Organics

![slide3](https://user-images.githubusercontent.com/22827786/38070274-e5dacee2-3366-11e8-98cc-3770500f7632.JPG)

![slide4](https://user-images.githubusercontent.com/22827786/38070237-b0d978e2-3366-11e8-948c-108a2f7e4ad9.JPG)

![slide5](https://user-images.githubusercontent.com/22827786/38070281-ec345ad8-3366-11e8-8276-d270fd299249.JPG)

![slide6](https://user-images.githubusercontent.com/22827786/38070285-f247dd1e-3366-11e8-9e38-3146e9a19897.JPG)

**Comment by AnaBelgun** [comment]
@meh9 does this happen because of the same reason as for the Innovation map (2016 regions changed) and I need to follow up with the ABBA team to update csvs?

**Comment by meh9** [comment]
I can't reproduce this issue - I don't get any error. Can you confirm if this is still happening?

**Comment by EhsanCanberra** [comment]
The reported layers appear to be working now
