### ISSUE TITLE
AREMI v2018-03-26 pre-release test - Observation - Symbol out of scale?

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/aremi-natmap#216]
Symbol out of scale?

Layer: Electricity Infrastructure/Transmission/Western Australia/Future Substations/Terminals/Power Stations/APR Information

![slide7](https://user-images.githubusercontent.com/22827786/38070358-57fec46a-3367-11e8-97ad-ed6a545dd5e4.JPG)

**Comment by AnaBelgun** [comment]
yep, this looks wrong. I forwarded the issue to Western Power.

**Comment by AnaBelgun** [comment]
Reply from Western Power: 
Hi Ana,

It’s not a symbolisation error although I can see how it could be interpreted that way. 

The future substation layer is speculative to a degree, and as such the exact location of the substation cannot be confidently determined. As a result we symbolise a large area where the substations are likely to be built.  

Regards

**Comment by AnaBelgun** [comment]
@EhsanCanberra Please see the above explanation from Western Power. There's nothing we can do at our end. 
I'll close this one for now.
