### ISSUE TITLE
 AREMI v2018-03-26 pre-release test - Error loading all layers of the Topography/Land/Geology group

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/aremi-natmap#217]
Error loading all layers of the Topography/Land/Geology group

Error Status code 500

![slide10](https://user-images.githubusercontent.com/22827786/38070511-0de6ad10-3368-11e8-8a3a-cb27ece95c09.JPG)

![slide11](https://user-images.githubusercontent.com/22827786/38070520-16f4cf4a-3368-11e8-8e0d-c768d9031f33.JPG)

**Comment by meh9** [comment]
Confirmed - service returns `500 Internal Server Error`. We need to get the data custodian to fix.

**Comment by AnaBelgun** [comment]
Custodian is GA; the data appears briefly for a second before the error message comes up.
I'll let Steven Ackerly know.

**Comment by meh9** [comment]
This group of layers has been removed.
