### ISSUE TITLE
AREMI v2018-03-26 pre-release test - Error loading Catalogue item - ABS (Beta) layers

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/aremi-natmap#218]
Error loading catalogue items:

Layer: Population/Australian Bureau of Statistics (BETA)/ABS Data Service/B05 Registered Marital Status by Age by Sex

Layer: Population/Australian Bureau of Statistics (BETA)/ABS Data Service/B05 Registered Marital Status by Age by Sex

![slide12](https://user-images.githubusercontent.com/22827786/38070640-b1ac6ba6-3368-11e8-8bf0-a06829d59c06.JPG)

![slide13](https://user-images.githubusercontent.com/22827786/38070646-b9c82140-3368-11e8-9fb4-1f2386c0601e.JPG)

**Comment by meh9** [comment]
These seem to be working, can you confirm they now work?

**Comment by EhsanCanberra** [comment]
The reported layers are working for me now.
