### ISSUE TITLE
 AREMI v2018-03-26 pre-release test - Error loading Environment group layers

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/aremi-natmap#219]
Error accessing catalogue items - Status code 502

Layer: Environment/Collaborative Australian Protected Areas Database (CAPAD)
Layer: Environment/Conservation Management Zones
Layer: Environment/Key Ecological Features
Layer: Environment/National Heritage List (NHL)

![slide14](https://user-images.githubusercontent.com/22827786/38070815-94106aa6-3369-11e8-8718-b06113834198.JPG)

![slide15](https://user-images.githubusercontent.com/22827786/38070820-9a1e4120-3369-11e8-911d-d5ebfbafebe6.JPG)

![slide16](https://user-images.githubusercontent.com/22827786/38070826-a0743d9a-3369-11e8-92b6-8a89b3fdb51e.JPG)

![slide17](https://user-images.githubusercontent.com/22827786/38070831-a92010ae-3369-11e8-98b9-5e82ad9a0d1d.JPG)

**Comment by meh9** [comment]
These layers all work now so it was probably a temporary issue.

Can you confirm these are now working?

**Comment by EhsanCanberra** [comment]
The reported layers are working for me now.
