### ISSUE TITLE
 AREMI v2018-03-26 pre-release test - Error running Analysis Tools

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/aremi-natmap#220]
Error running the Renewable Energy/Wave/Australian Wave Energy Atlas/Analysis Tools

![slide18](https://user-images.githubusercontent.com/22827786/38071154-68578cf8-336b-11e8-8750-c5cc6a93c7bc.JPG)

![slide19](https://user-images.githubusercontent.com/22827786/38071159-6e75fe76-336b-11e8-91c0-9fbc89f2348a.JPG)

**Comment by meh9** [comment]
The Wave Atlas is now working again.
