### ISSUE TITLE
 AREMI v2018-03-26 pre-release test - Observation - Map Scale display

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/aremi-natmap#221]
Just observed that map scale displays up to 500 Km, zooming out further removes the display!
Is it meant to be that way?

![slide22](https://user-images.githubusercontent.com/22827786/38071234-e42f26b0-336b-11e8-8968-3fd2e061035f.JPG)

![slide23](https://user-images.githubusercontent.com/22827786/38071236-eac32dc8-336b-11e8-862d-b5e571f52b2d.JPG)

**Comment by meh9** [comment]
Once zoomed out where the entire globe is visible the scale display does indeed disappear. I'm ok with that as it isn't very useful at that scale.
