### ISSUE TITLE
Update QLD Bioenergy layers

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/aremi-natmap#225]
Hi, 

We want to totally remove some of the data published in AREMI and replace some with new data. Some of the infrastructure datasets we will not be publishing again as these are available already in other parts of AREMI (e.g cane railways). We also will not be publishing land use data. 

I have mapped out a bit of a new structure (below) for how we would like the Queensland data set out. Any field ending in a * will be a separate CSV file with individual metadata. The names are not the final ones but you get an idea of how many dataset are coming. Each CSV will be loaded to the data.qld.gov.au portal in one section (similar to this datasets here https://data.qld.gov.au/dataset/queensland-confidential-species). 

I have attached two examples of what the data will look like as CSVs and the accompanying metadata (this will be similar for all of the data) – they are still draft sorry but will give you an idea of how the data looks - the field in the CSV to show in AREMI is the total residues field. 

I have just gotten approval to start loading this to the qld open data portal so hopefully this can get done soon. When this is done I will send you the link and you can check any issues with connecting to that particular portal.  

In terms of styling we have no real preference at all. Happy to go with the default styling that happens when you drag and drop the CSV files into the AREMI platform – but we can work with you to adjust anything needed.

**Comment by AnaBelgun** [comment]
Data available here: https://drive.google.com/drive/folders/1sRYz6ShfBvK-QMlDitVWpSUKDes9XLPa

**Comment by meh9** [comment]
Waiting for custodian to make the layers available.

**Comment by AnaBelgun** [comment]
Data updated and ready to be harvested through data.qld.gov.au 

https://data.qld.gov.au/dataset/australian-biomass-for-bioenergy-assessment

**Comment by meh9** [comment]
The old groups are in here, suggest you reuse these files:

https://github.com/TerriaJS/aremi-natmap/tree/master/datasources/aremi/custodian/QLD_Department_of_Science_Information_Technology_and_Innovation

Then link these files back in by reverting this:

https://github.com/TerriaJS/aremi-natmap/commit/567ccff642d04cfba7b4a230ac5240ee7e875982#diff-692b030d1294ca472e4261f08a3382c3

You may be able to do something like this but either with a `resourceId` instead of `datasetId`, or `datasetId` with a filter to only include specific ones:

https://github.com/TerriaJS/aremi-natmap/blob/3b38c4848284ba80a0fb81a03e96845fed910678/datasources/aremi/custodian/National_Native_Title_Tribunal/Native_Titles.ejs

**Comment by meh9** [comment]
something like this existing one:

```
            {
              "name": "Taxation Statistics",
              "type": "group",
              "items": [
                {
                  "name": "Taxation Statistics 2011-2012",
                  "id": "Root Group/National Data Sets/Social and Economic/Taxation Statistics 2011-2012",
                  "type": "ckan-resource",
                  "url": "https://data.gov.au",
                  "datasetId": "taxation-statistics-2011-12",
                  "resourceId": "205ef0d1-521b-4e3c-a26c-4e49e00f1a05"
                },
```

**Comment by a-stacey** [comment]
There is no Queensland -> Livestock -> Dairy Manure layer that I could see.
Corrected Naive -> Native in Naive Forest - Cypress.

**Comment by a-stacey** [comment]
There is also an issue with these layers in that they seem to be blocked via proxys other then the nationalmap proxy.

**Comment by KellyBryant1** [comment]
Hi, I am the data custodian for those layers. With regards to the Dairy manure layer - this layer does not exist. We ran out of time to get this published so it will have to go in another release.

**Comment by AnaBelgun** [comment]
@a-stacey @meh9: looks like we can go ahead without the Dairy manure in this release

**Comment by meh9** [comment]
We've looked into this again, and it seems we need to find a different way to access the files - the Incapsula I'm-not-a-robot protection blocks us because we can't get the user to confirm they are not a robot.

**Comment by a-stacey** [comment]
Did you also confirm it working with the NM proxy? and if so do we have any idea why it works for the NM proxy but not the AREMI proxy (i.e. whitelisted?).

**Comment by meh9** [comment]
Currently discussing with data custodian.

**Comment by AnaBelgun** [comment]
Custodian messaged today 8 Aug and investigating.

**Comment by meh9** [comment]
Work complete, have emailed stakeholder to check on prototype.
