### ISSUE TITLE
Update WA Bioenergy data - add forestry 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/aremi-natmap#226]
Add the forestry data from WA team. 
Forestry data file: ???

**Comment by meh9** [comment]
Waiting for them to create services and supply the URL's to us.

**Comment by AnaBelgun** [comment]
The NFI services have now been configured and are now available for consumption.  The URL is as shown below and the layers are as follows:

•	https://www.agric.wa.gov.au/geoserver/NFI/wms?
•	Hardwood_NFI_Plantations_2016
•	Hardwood_NFI_Yields
•	Softwood_NFI_Plantations_2016
•	Softwood_NFI_Yields

**Comment by meh9** [comment]
Have added the services and am currently discussing some issues and metadata with WA.

**Comment by meh9** [comment]
There's now some Abstracts in there so I'm going to consider this as done.
