### ISSUE TITLE
ABBA - QLD - message to users data not available

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/aremi-natmap#232]
With regards to taking down the current Queensland data from AREMI and re-publishing all of our data using CSV files in the Qld data portal. I would like to stop the web service now whilst I load the new information to the data portal so that there isn’t two different sets of Queensland data online at the same time (in AREMI and in the Qld data portal). 

Would it be possible to put a sentence on the home page for Queensland (below) for the moment which says something like “Data currently not available” or “Data being updated” ? 

If users query the data, direct them to QLD team

**Comment by AnaBelgun** [comment]
message text: 
Data for Queensland is currently being updated. 
Any enquiries about Queensland biomass data can be directed to Kelly.Bryant@des.qld.gov.au

**Comment by meh** [comment]
@meh9 ^

**Comment by meh9** [comment]
Fixed.
