### ISSUE TITLE
Investigate error loading layers of the Topography/Land/Geology group

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/aremi-natmap#238]
Error accessing catalogue item
All layers of group: Topography/Land/Geology

**Note:** The same issue noted in recent tests for National Map - I understand the issue has been resolved in National Map. 

Comment from GA Enterprise GIS – Platform Administrator below:
"I have spoken with Ben and we have performed testing on the Surface Geology web service. Testing has shown that it is working correctly with National Map and that the issue appears to be isolated to AREMI."

![slide1](https://user-images.githubusercontent.com/22827786/41638535-6ab31390-7449-11e8-8232-1f8b30c449ec.JPG)

![slide2](https://user-images.githubusercontent.com/22827786/41638542-730e4870-7449-11e8-8192-2d75e6eb2736.JPG)

![slide3](https://user-images.githubusercontent.com/22827786/41638552-7c3ee62a-7449-11e8-92bb-ec8cbfaa5d44.JPG)

![slide4](https://user-images.githubusercontent.com/22827786/41638588-bcec0f5e-7449-11e8-94a5-384b1f32f96a.JPG)

![slide5](https://user-images.githubusercontent.com/22827786/41638603-c6c067e6-7449-11e8-9679-54ff22e94794.JPG)

![slide6](https://user-images.githubusercontent.com/22827786/41638607-cf525784-7449-11e8-9f99-a051390a5045.JPG)

**Comment by meh9** [comment]
Retested including in NationalMap, could not get the service working. Removing the service as it's not used much anyway.
