### ISSUE TITLE
AREMI v2018-05-25 post-release test - Could not run any Wave Analysis Tool

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/aremi-natmap#240]
**Failed to run any Analysis Tool** in - Renewable Energy/Wave/Australian Wave Energy Atlas/Analysis Tools

**Error message:**
"Web Processing Service Invocation failed. More details are available on the Info panel"

Nothing displayed in my Info panel!

![slide10](https://user-images.githubusercontent.com/22827786/41639002-aa93ea14-744b-11e8-8068-6cac0d4a2859.JPG)

![slide11](https://user-images.githubusercontent.com/22827786/41639006-b0e9ba42-744b-11e8-9296-126496b28ac7.JPG)

**Comment by meh9** [comment]
This service is now working again:

<img width="397" alt="screen shot 2018-08-17 at 18 59 23" src="https://user-images.githubusercontent.com/5283003/44257560-b8b84400-a24f-11e8-9a86-e12c0a5c2799.png">
