### ISSUE TITLE
AREMI v2018-05-25 post-release test - Observation - Very slow data load - 1

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/aremi-natmap#241]
Observation: Slow in loading the data
Layer: Infrastructure/Marine Infrastructure Lines

![slide12](https://user-images.githubusercontent.com/22827786/41639088-0fefe8ae-744c-11e8-8c64-dca872ad0bdd.JPG)

**Comment by meh9** [comment]
Service performance is now acceptable.
