### ISSUE TITLE
AREMI v2018-05-25 post-release test - Error loading ABS Data Service layer

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/aremi-natmap#246]
Error: Error accessing catalogue item
Layer: Layer: Population/Australian Bureau of Statistics (BETA)/ABS Data Service/B01 Selected Person Characteristics

![slide17](https://user-images.githubusercontent.com/22827786/41639400-2178c694-744d-11e8-961f-90f73757389c.JPG)

**Comment by meh9** [comment]
Cannot reproduce - possible temporary issue.
