### ISSUE TITLE
Add ABS boundaries group

### ISSUE THREAD

**Issue by meh9** [TerriaJS/aremi-natmap#249]
We should add the ABS boundaries MapServer as a group of layers:

http://censusdata.abs.gov.au/arcgis/rest/services/ASGS2016/ASGS2016BoundariesOnline/Mapserver

Issues to solve:

- [ ] ask ABS if they are ok with it?
- [ ] find what license it is under (probably CC-BY)
- [ ] find a list spelling out what the codes in the layer names mean, and set that as the group description so that you see it when you click on the group

**Comment by kring** [comment]
This already exists in NationalMap under Data Providers.

**Comment by Jason-DNetto** [comment]
I found http://www.abs.gov.au/websitedbs/D3310114.nsf/home/Australian+Statistical+Geography+Standard+(ASGS) which has most of the 2016 codes except AUS,STATE and DZN

**Comment by meh9** [comment]
@kring so it does! That looks perfect, has the proper names and everything, so looks like we can just copy that into AREMI, perfect!

How did we end up with that, did we do it or did they?

**Comment by meh9** [comment]
@Jason-DNetto have a look at https://nationalmap.gov.au/ -> Data Providers -> ABS Statistical Boundaries, does it have everything you need? If so we can easily put the same hierarchy into AREMI.

<img width="395" alt="screen shot 2018-06-22 at 15 16 37" src="https://user-images.githubusercontent.com/5283003/41759007-6761eec2-762f-11e8-9add-776ca178517a.png">

**Comment by Jason-DNetto** [comment]
@meh9  that hierarchy does not have some of the layers present in the service, such as state boundaries or mesh blocks. As to what i need, research projects have a tendency to 'need' everything. I can't guarantee the ABBA members wont start suddenly using mesh blocks. 

For my purposes I can cope best with the querying the group layer URL, and would prefer a group url, but i can understand if it is more useful for other users to sort by date.

**Comment by meh9** [comment]
@Jason-DNetto I've added this hierarchy for now, does it suit your needs:

https://geo.abs.gov.au/arcgis/rest/services/

**Comment by Jason-DNetto** [comment]
It has all the layers, so i can make it work with a few changes in my service.
