### ISSUE TITLE
AREMI v2018-08-06 Pre-Release Test - Group not available error 1

### ISSUE THREAD

**Issue by AngeloPACE** [TerriaJS/aremi-natmap#256]
Error: Group not available

Layer: Topography / Aerial/Satellite Imagery / Queensland / Sentinel-2.....

![slide1](https://user-images.githubusercontent.com/41311486/43934073-bbbb6912-9c90-11e8-95b9-6d6414580d7a.JPG)

![slide2](https://user-images.githubusercontent.com/41311486/43934079-c7ec0200-9c90-11e8-8fe0-e9cad6a92853.JPG)

**Comment by meh9** [comment]
This service has had upgrades since and now appears to be working much better.
