### ISSUE TITLE
AREMI v2018-08-06 Pre-Release Test - Group not available 2

### ISSUE THREAD

**Issue by AngeloPACE** [TerriaJS/aremi-natmap#257]
Error: Group not available

Layer: Topography / Aerial/Satellite Imagery / Australian Capital Territory / Landsat geomedian

![slide3](https://user-images.githubusercontent.com/41311486/43934397-89b5fd40-9c92-11e8-8b07-b206f3197c4c.JPG)

![slide4](https://user-images.githubusercontent.com/41311486/43934401-8de6df2e-9c92-11e8-9923-ad9256793dc9.JPG)

**Comment by meh9** [comment]
This service does indeed seem to have some problems right now.

**Comment by meh9** [comment]
This has now been fixed.
