### ISSUE TITLE
AREMI v2018-08-06 Pre-Release Test - Zoom in to text

### ISSUE THREAD

**Issue by AngeloPACE** [TerriaJS/aremi-natmap#258]
Error: Zoom in to - text appears on map and stays even after zooming.

![slide5](https://user-images.githubusercontent.com/41311486/43934563-531dac0a-9c93-11e8-933d-af53a1ebdfe3.JPG)
![slide6](https://user-images.githubusercontent.com/41311486/43934568-56cde428-9c93-11e8-8750-f8d2b9b00592.JPG)

**Comment by meh9** [comment]
This service does indeed seem to have some problems right now.

**Comment by meh9** [comment]
You need to zoom in more to see the layer data:

<img width="1680" alt="screen shot 2018-08-17 at 18 42 20" src="https://user-images.githubusercontent.com/5283003/44256724-55c5ad80-a24d-11e8-9ff8-6eef44854a51.png">
