### ISSUE TITLE
AREMI v2018-08-06 Pre-Release Test - Group not available 3

### ISSUE THREAD

**Issue by AngeloPACE** [TerriaJS/aremi-natmap#259]
Error: This data layer did NOT produce the 'group not available' error after having added to the view. It did however produce the error after randomly zooming in.
Layer: Topography / Aerial/Satellite Imagery / Australian Capital Territory / Landsat 16... / Landsat 8... / Landsat 8 false colour

![slide7](https://user-images.githubusercontent.com/41311486/43934950-11c3a1a4-9c95-11e8-91f0-78a8c64c3867.JPG)
![slide8](https://user-images.githubusercontent.com/41311486/43934953-15bad78c-9c95-11e8-99db-851354d6e662.JPG)

**Comment by meh9** [comment]
Unable to reproduce.

Note that NCI has a quarterly maintenance downtime window when nothing is available.

Please reopen this issue if it reoccurs.
