### ISSUE TITLE
Invalid dates in AEMO generation data CSV

### ISSUE THREAD

**Issue by kring** [TerriaJS/aremi-natmap#263]
The `Electricity Infrastructure -> Generation -> Current Power Generation - NEM` CSV (https://services.aremi.data61.io/aemo/v6/csv/all) has invalid dates in the `Most Recent Output Time (AEST)` column. They look like this:

`2018-08-16T14:00:00%z`

(note the `%z` instead of `Z` or `+10:00` on the end)

TerriaJS seems to mostly to be able to deal with this, but it does cause a (caught) exception during load.

**Comment by rowanwins** [comment]
No longer happens
