### ISSUE TITLE
ABBA - WA - update Hardwood residues

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/aremi-natmap#264]
Here is the URL to the new dataset for shire based hardwood residues. Could you use the third column, Total_Residues_Average(45t/h) as the display column please. Also can you now remove Hardwood NFI Yields and the Softwood NFI Yields from the AREMI website please. This data and some more to come will supersede it. Leave the NFI Plantations 2016 data up though. 

https://catalogue.data.wa.gov.au/dataset/93388cec-0f4d-47fe-8ab8-75a7969c9e3e/resource/4c51213d-1f0a-4ddd-9f6b-211e45694975/download/hardwood-biomass-2019-2029.csv

**Comment by AnaBelgun** [comment]
Update from WA team: 
Hi Ana

Here is the URL for the Softwood Plantation dataset. Let me know if there are any issues. I did do a quick upload and noticed that the shire of Murray in NSW is being picked up instead of the one in the South West of WA. 

https://catalogue.data.wa.gov.au/dataset/fc778541-acab-40ec-ac0d-e939d85960f3/resource/3ab18414-b7ae-4da6-be74-4a7ebc0f036c/download/softwood-plantation-residues2016.csv


Regards

**Comment by meh9** [comment]
Done.

Advising data custodian to use LGA_CODE_2011 instead.
