### ISSUE TITLE
Replace all VIC data urls with updated ones

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/aremi-natmap#266]
Due to issues during the process of creating urls for their csv files, the VIC team has requested to replace all urls with updated versions. Needed for a demo on 26th of Sept. 

Document with all urls by email and here: https://drive.google.com/drive/folders/15Crgqrj4fjAoXXKHyYBD5eyba9Sa98ko

**Comment by AnaBelgun** [comment]
@meh9 let me know if you have any questions

**Comment by meh9** [comment]
Fixed in #267.

**Comment by meh9** [comment]
And updated in #268
