### ISSUE TITLE
AREMI v2018-09-28 Pre-Release Test - Color scale range update feature

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/aremi-natmap#272]
The Color Scale Range Update by user feature is great! Users will definitely find it useful and love it.

Curiously, I have tested some values in the range input boxes - all worked fine.

However, you may have to **add a 'range-boundary' check** to validate before committing update. 
For example, as shown in Slide 4, the range of the data is 27.5 (max) and 9.5 (min). 
I have changed that to 1 (max) and 0 (min) -- both numbers are outside the above range -- and commit Update Range (Slide 5)
Interestingly, it did accept that and then blacked out all the data (Slide 6). Is this expected?  :)

Ps. Found the following tests that have been implemented: negative number (Slide 7), max<min (Slide 8)

![slide4](https://user-images.githubusercontent.com/22827786/46519233-e5d1bc00-c8ba-11e8-9a20-6f7a2231e83b.JPG)

![slide5](https://user-images.githubusercontent.com/22827786/46519240-ea967000-c8ba-11e8-8228-2d1d44ba06fb.JPG)

![slide6](https://user-images.githubusercontent.com/22827786/46519245-ee29f700-c8ba-11e8-8c53-63235bb6cdd5.JPG)

![slide7](https://user-images.githubusercontent.com/22827786/46519260-faae4f80-c8ba-11e8-97f0-1537936740f6.JPG)

![slide8](https://user-images.githubusercontent.com/22827786/46519265-ff730380-c8ba-11e8-8c43-50be3eceec41.JPG)

**Comment by AnaBelgun** [comment]
This is probably a setting for the BoM server @meh9?

**Comment by meh9** [comment]
As far as I know it's not possible to actually get the min/max values of the data ahead of time from ncWMS - you have to either get the default and read the legend to find min/max, or experiment yourself, so there is little we can do about this.
