### ISSUE TITLE
 AREMI v2018-09-28 Pre-Release Test - Bioenergy - National Biogas facilities 404 error

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/aremi-natmap#273]
Layer: Renewable Energy/Bioenergy/National/Biogas Facilities
Error: Unable to load CSV file

![slide9](https://user-images.githubusercontent.com/22827786/46519586-3b5a9880-c8bc-11e8-971c-db4196fbb369.JPG)

**Comment by AnaBelgun** [comment]
Seems to be broken although custodian fixed it few weeks ago - University of Southern Queensland notified again.

**Comment by meh9** [comment]
Now working again.
