### ISSUE TITLE
AREMI v2018-09-28 Pre-Release Test - ABARES - DGA - CLUM 2016 - not loading

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/aremi-natmap#274]
Layer: Renewable Energy/Bioenergy/National/Catchment Scale .. May 2016 
Extremely slow, nothing displayed, hangs (?)

![slide10](https://user-images.githubusercontent.com/22827786/46519697-a015f300-c8bc-11e8-83b5-a3ca61b7cc19.JPG)

**Comment by maxious** [comment]
2016 CLUM in ckan gets ID e918... which is at the end of the list of raster layers so if something goes wrong earlier it always suffers. Anyway, it is fixed again now.

**Comment by AnaBelgun** [comment]
awesome, thank you @maxious; all good now
