### ISSUE TITLE
AREMI v2018-09-28 Pre-Release Test - Bioenergy - NSW data - very slow

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/aremi-natmap#275]
Datasets: Renewable Energy/Bioenergy/New South Wales/**
NSW layers are very slow in loading

![slide11](https://user-images.githubusercontent.com/22827786/46519845-33e7bf00-c8bd-11e8-8f63-9671cc85ce34.JPG)

**Comment by AnaBelgun** [comment]
Re-tested and they seem to work better now.
