### ISSUE TITLE
AREMI v2018-09-28 Pre-Release Test - Bioenergy - SA - reduced rainfall

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/aremi-natmap#276]
Layer: Renewable Energy/Bioenergy/South Australia/Agriculture/Simulated Residual Straw/5% Reduced Rainfall
Error: Error accessing catalogue item - Status code: 502

![slide12](https://user-images.githubusercontent.com/22827786/46519936-8d4fee00-c8bd-11e8-949c-9baf1b77a3b6.JPG)

**Comment by AnaBelgun** [comment]
can confirm it works initially, but then dissapears and throws a 502 error.
The SA team was working on some of their services recently. I'll forward the issue.

**Comment by AnaBelgun** [comment]
Will close for now and re-open if error needs to be fixed at terriajs end.
