### ISSUE TITLE
AREMI v2018-09-28 Pre-Release Test - Environment - Commonwealth Marine Reserves error

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/aremi-natmap#277]
Layer: Environment/Commonwealth Marine Reserves
Error: Error accessing catalogue item - Status code: 502

![slide13](https://user-images.githubusercontent.com/22827786/46520000-c12b1380-c8bd-11e8-84e6-b754dda62b9a.JPG)

**Comment by AnaBelgun** [comment]
This seems to work now:

![image](https://user-images.githubusercontent.com/18452161/46592969-4e1ada80-cb13-11e8-8020-a83ffe2d32ac.png)
