### ISSUE TITLE
AREMI v2018-09-28 Pre-Release Test - Environment - NRM regions service error

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/aremi-natmap#278]
Layer: Boundaries/Natural Resource Management Regions
Error: No layer found

![slide14](https://user-images.githubusercontent.com/22827786/46520137-2d0d7c00-c8be-11e8-9763-92898e164102.JPG)

**Comment by AnaBelgun** [comment]
@meh9 This is strange; the service works fine on NatMap 
http://nationalmap.gov.au/#share=s-erTPJQWSNYIhrpuMx6tfm9EZ6ml

to investigate

**Comment by meh9** [comment]
The layer had changed name on the service - fixed.
