### ISSUE TITLE
AREMI v2018-09-28 Pre-Release Test - Error loading Elevation data

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/aremi-natmap#280]
Layer: Topography/Elevation/Aspect
Error: An error occurred - Request has failed - Status code: 503

![slide16](https://user-images.githubusercontent.com/22827786/46520355-08fe6a80-c8bf-11e8-9c8c-f501f6b32d3b.JPG)

**Comment by meh9** [comment]
All 503/504 errors from this data custodian is related to TerriaJS/terriajs#3092
