### ISSUE TITLE
AREMI v2018-09-28 Pre-Release Test - Error loading Hydrography data

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/aremi-natmap#284]
Layer: Topography/Water/Australian Hydrography
Error: Request has failed - Status code: 503

![slide20](https://user-images.githubusercontent.com/22827786/46520677-3a2b6a80-c8c0-11e8-9c53-e64dcb574c78.JPG)

**Comment by meh9** [comment]
Fixed in https://github.com/TerriaJS/aremi-natmap/issues/291
