### ISSUE TITLE
AREMI v2018-09-28 Pre-Release Test - QLD flood data - update service url

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/aremi-natmap#288]
Layer: Topography/Water/Floods/Queensland/QLD Floods 2011
Error: Request has failed - Status code: 503

![slide24](https://user-images.githubusercontent.com/22827786/46521276-69db7200-c8c2-11e8-9494-eb52c4a34b91.JPG)

**Comment by AnaBelgun** [comment]
It looks like the services have been changed. 
To replace the current one with https://gisservices.information.qld.gov.au/arcgis/rest/services/InlandWaters

**Comment by meh9** [comment]
The Flood layers have been removed as the service is no longer available, and the suggested replacement is not equivalent.
