### ISSUE TITLE
AREMI v2018-09-28 Pre-Release Test - GA River Regions 503 error

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/aremi-natmap#291]
Layer: Topography/Water/River regions
RuntimeError: Invalid XMLHttpRequest response type

![slide27](https://user-images.githubusercontent.com/22827786/46521575-5977c700-c8c3-11e8-8a5f-c7bfc3d2cea2.JPG)

**Comment by AnaBelgun** [comment]
tested this as part of the service http://services.ga.gov.au/gis/rest/services/Surface_Hydrology_WM/MapServer
and it returns a 503 error

**Comment by meh9** [comment]
This was actually a configuration error. To resolve it I made the following catalogue changes: 

* Renamed the two identical layers "Australian Hydrography" to "Surface Hydrology" to reflect the new service data.
* Removed the layer "Topography -> Water -> River regions" as the service is no longer available.

This will be in the next catalogue update.
