### ISSUE TITLE
AREMI v2018-09-28 Pre-Release Test - ABS dataservice error message

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/aremi-natmap#292]
Layer: Population/Australian Bureau of Statistics (BETA)/ABS Data Service/B01 Selected Person Characteristics
Error: Request has failed

![slide28](https://user-images.githubusercontent.com/22827786/46521663-9e9bf900-c8c3-11e8-842c-8b50705179be.JPG)

**Comment by AnaBelgun** [comment]
Error message appears when opening the catalogue item for the first time; error message dissapears when click on "ok" and data is shown on the map.

**Comment by meh9** [comment]
It appears this was a problem at the ABS end as all layers are now working normally with no error messages.
