### ISSUE TITLE
AREMI v2018-09-28 Pre-Release Test - Error accessing base map

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/aremi-natmap#294]
Issues encountered while testing the **Map View** and **Base Map** options - on Friday 5 October 2018 morning 9 am to 12 noon.

1. Test covers all possible combinations of Map View and Base Map options
2. The 'Australian Topography' base map generated error when Map View option was changed from 2D to 3D and 3D Smooth (Slides 31-34)
3. Worked fine in 2D (Slides 35-36)
4. Second attempt on a different layer produced the same error (Slides 37-38)

![slide31](https://user-images.githubusercontent.com/22827786/46522364-ed4a9280-c8c5-11e8-83db-756d9f8f6df5.JPG)

![slide32](https://user-images.githubusercontent.com/22827786/46522382-f89dbe00-c8c5-11e8-9dbc-085ea1f4af61.JPG)

![slide33](https://user-images.githubusercontent.com/22827786/46522396-fdfb0880-c8c5-11e8-85ef-2cb916707b53.JPG)

![slide34](https://user-images.githubusercontent.com/22827786/46522403-03585300-c8c6-11e8-93f8-c8da4728756f.JPG)

![slide35](https://user-images.githubusercontent.com/22827786/46522413-081d0700-c8c6-11e8-83b7-68571bfbe3b1.JPG)

![slide36](https://user-images.githubusercontent.com/22827786/46522421-0bb08e00-c8c6-11e8-84d0-3b7210b5a754.JPG)

![slide37](https://user-images.githubusercontent.com/22827786/46522720-e83a1300-c8c6-11e8-8667-4c2f342eb947.JPG)

![slide38](https://user-images.githubusercontent.com/22827786/46522730-ee2ff400-c8c6-11e8-962b-d3cf1895cdd1.JPG)

**Comment by meh9** [comment]
All 503/504 errors from this data custodian is related to https://github.com/TerriaJS/terriajs/issues/3092
