### ISSUE TITLE
AREMI v2018-09-28 Pre-Release Test - Observation - Share function in different browsers

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/aremi-natmap#296]
**Observation**

Test of 'Share' function in different browser

Master in Chrome Version 69.0.3497.100 (Slide 40) - Original
Copy in Chrome Version 69.0.3497.100 (Slide 41) - Exact replica
Copy in IE Version 11.0.9600.19129 (Slide 42) - Exact replica
Copy in Firefox Version 60.2.2esr (Slide 43) - Exact replica with a warning **'Unusually Slow Performance Detected'**

Unclear why Mozilla Firefox generated that warning!

![slide40](https://user-images.githubusercontent.com/22827786/46523498-394b0680-c8c9-11e8-8154-a854a050989e.JPG)

![slide41](https://user-images.githubusercontent.com/22827786/46523527-4ec03080-c8c9-11e8-92d9-e36ca49cd342.JPG)

![slide42](https://user-images.githubusercontent.com/22827786/46523536-58499880-c8c9-11e8-8fb1-2c781d06b1f9.JPG)

![slide43](https://user-images.githubusercontent.com/22827786/46523545-5da6e300-c8c9-11e8-86af-67d3ecc70a53.JPG)

**Comment by meh9** [comment]
That just means TerriaJS thought things were running too slowly on your computer and it switched to 2D mode to make things faster. This could be for any number of reasons like background processes, not enough memory so it's busy using swap etc.
