### ISSUE TITLE
Investigate ABBA - NSW data error in 2D

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/aremi-natmap#302]
When accessing ABBA - NSW Cereal Straw layers in 2D, we get this error message: 

![image](https://user-images.githubusercontent.com/18452161/48028780-89570a80-e1a0-11e8-9191-5e440fc8fcdd.png)

All layers under NSW group do not work in 2D. 

The spatial layers are created with ArcGIS in EPSG:4283 to match DPI geodatabases where they are hosted.

Could projected versus geodetic coordinate system be the problem? It wasn't in the past but perhaps AREMI can no longer transform the projection on the fly?

Would simply changing the projection of the projects to EPSG:3857 and then publishing again be a potential solution? Would the published layer take on the ArcGIS project defined projection or the DPI geodatabase projection where the layer resides?

**Comment by AnaBelgun** [comment]
@meh9 to change the WMS setting (to the ArcGIS MapServer) so the graphics of the legend and Feature Information fields are better displayed. For 22 layers.

**Comment by meh9** [comment]
Done but not released: https://github.com/TerriaJS/aremi-natmap/commit/d304dcbd5c5ead66271f3f565b39d9cb81e68025

**Comment by AnaBelgun** [comment]
@meh9 all layers needs now to have the WMS settings changed based on the update of the MXD format
