### ISSUE TITLE
Adjust NOM constraint map legends for final release

### ISSUE THREAD

**Issue by elangham** [TerriaJS/aremi-natmap#307]
1. On proposed_investment.csv display variable "Investment Year" change range from 2016-2026 to 2017-2029...or ideally we could just automate it from the data range but maybe there is a reason we didn't do that last year?
2. Is it possible to reassign colours on proposed_investment.csv display variable "Constraint Season" to blue for winter and green for summer+winter? (currently not intuitive but that’s what the current public maps look like so it may not be fixable)
@meh9

**Comment by meh9** [comment]
Re 1, the range is as far as I can see calculated automatically from the min/max years in the data. I don't know why the years were not updated last year.

**Comment by meh9** [comment]
Have just set specific colours for Constraint Season:

<img width="782" alt="screen shot 2018-12-03 at 17 14 14" src="https://user-images.githubusercontent.com/5283003/49356181-fe295000-f71e-11e8-9353-20cd0b3bd47e.png">

**Comment by elangham** [comment]
Great! New colours look tops - although looks like they’re at 0% transparency whereas the others like Asset Type might be a slightly higher value, but not a problem if can’t be adjusted.

**Comment by elangham** [comment]
Strangely the legend range for Investment_year still hasn't updated to match the new dataset? Any clues?

**Comment by elangham** [comment]
Yeah go for 2018-2028, thanks!

**Comment by meh9** [comment]
Done.
