### ISSUE TITLE
Update Biogas facilities url

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/aremi-natmap#333]
Currently the Biogass Facilities (under Renewables - Bioenergy - National) is broken: https://www.nationalmap.gov.au/renewables/#share=s-aoA92GYxHIj4Q6aV

The url is dated, and it should be replaced with: https://biogas.usq.edu.au/data/biogas.csv

**Comment by reginapramesti** [comment]
Already fixed by #334
