### ISSUE TITLE
Investigate and fix AEMO data - 30 days not available 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/aremi-natmap#339]
the AEMO data - generation for the NEM power stations, used to have available the values for 30 days back; now it only has for 1 and 7 days 

![image](https://user-images.githubusercontent.com/18452161/55296053-312ae880-5460-11e9-8ce7-1079e984e079.png)
https://nationalmap.gov.au/renewables/#share=s-tWbcnfI0IsK8ekJ0

**Comment by meh9** [comment]
I think this was a CSS problem, and it now looks fixed. Not sure exactly which issue resolved it though.

**Comment by AnaBelgun** [comment]
yes, disregard please my previous comment; it shows fixed in the pre-prod version
![image](https://user-images.githubusercontent.com/18452161/56784445-d5bc0280-6833-11e9-8880-2657ad6e1001.png)
