### ISSUE TITLE
Expand and Download dropdowns of AREMI power generation layers have 1m and 3m options obscured

### ISSUE THREAD

**Issue by steve9164** [TerriaJS/aremi-natmap#340]
Expand and Download dropdown buttons are not wide enough to display the 1m and 3m options.
https://nationalmap.gov.au/renewables/#share=s-2fKm5PD51FzICJB8
![image](https://user-images.githubusercontent.com/13863530/55308668-234c8600-54a7-11e9-9c87-c1771ba272c3.png)

**Comment by meh9** [comment]
That sounds like maybe it explains this? https://github.com/TerriaJS/aremi-natmap/issues/339

**Comment by steve9164** [comment]
See #339.
