### ISSUE TITLE
AREMI - April 2019 release 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/aremi-natmap#342]
Checklist for April 2019 release: 

- [x] latest version of TerriaJS (if possible with: story feature - TerriaJS/terriajs#3228, AEC boundaries new regionning TerriaJS/terriajs#3277; parallax issue TerriaJS/terriajs#3288)

- [x] https://github.com/TerriaJS/aremi-natmap/pull/341 - this needs to an update

- [ ] https://github.com/TerriaJS/aremi-natmap/issues/336

- [x] https://github.com/TerriaJS/aremi-natmap/issues/333

- [x] https://github.com/TerriaJS/aremi-natmap/issues/339

- [x] https://github.com/TerriaJS/aremi-natmap/issues/343

- [x] https://github.com/TerriaJS/aremi-natmap/issues/338

**Comment by meh9** [comment]
The prototype site now has a new version except for #331, still waiting for a Go from Ed about that.

**Comment by meh9** [comment]
Heard back from Ed saying they do not have approval to release yet, so #331 will have to wait for next AREMI release.

**Comment by meh9** [comment]
New version released and sent to GA.
