### ISSUE TITLE
Update AREMI to latest TerriaJS master and re-release

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/aremi-natmap#346]
- [x] Update to latest terria master to include this PR: https://github.com/TerriaJS/terriajs/pull/3288 

- [ ] wait until WA ABBA confirms they are happy with current changes in the latest AREMI release - pending

- [x] re-release to GA

**Comment by meh9** [comment]
Updated TerriaJS and re-released. WA ABBA sent a small number of changes which we can publish separately.
