### ISSUE TITLE
Disable DoubleClick in Google Analytics account

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/aremi-natmap#349]
We’re not explicitly/purposely connecting to stats.g.doubleclick.net, but Google Analytics Google Analytics will connect to that domain when Google Analytics is configured in a certain way:
https://tonnygaric.com/blog/prevent-google-analytics-from-making-requests-to-stats-g-doubleclick-net

**Comment by meh9** [comment]
The feature has been disabled as detailed in the blog post above.
