### ISSUE TITLE
Update Land tenure services

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/aremi-natmap#355]
Replace land tenure url with the new one
http://prod-arcgis-stack-1.gis.ga.gov.au/gis/rest/services/Australian_Land_Tenure/MapServer

**Comment by KeyboardSounds** [comment]
@AnaBelgun that url doesn't seem to work, it returns a 500 error

**Comment by AnaBelgun** [comment]
same problem as Cadastre probably. I'll ask GA to check again

**Comment by AnaBelgun** [comment]
working faster now; @kring would you please comment here what was the change you made?

**Comment by kring** [comment]
This was the change: https://github.com/TerriaJS/aremi-natmap/pull/363
