### ISSUE TITLE
Different colours in new release

### ISSUE THREAD

**Issue by meh9** [TerriaJS/aremi-natmap#365]
The new AREMI release has ever so slightly different colours after the TerriaJS/NatMap upgrade:

Old:
<img width="355" alt="Screen Shot 2019-06-14 at 09 36 51" src="https://user-images.githubusercontent.com/5283003/59473929-f85bb680-8e87-11e9-9419-94f1f60a53de.png">

New:
<img width="353" alt="Screen Shot 2019-06-14 at 09 36 38" src="https://user-images.githubusercontent.com/5283003/59473937-feea2e00-8e87-11e9-9f3f-a24ddbe62f33.png">

Maybe we're not actually including the AREMI CSS? Or maybe we merged over something when merging latest NatMap?

**Comment by philipgrimmett** [comment]
From memory AREMI never had a custom colour palette and always defaulted to stock Terria.

**Comment by chloeleichen** [comment]
I created a PR to give us the options to have the old color just on Aremi if that's what we want
