### ISSUE TITLE
AREMI share links using NOM layers broken

### ISSUE THREAD

**Issue by elangham** [TerriaJS/aremi-natmap#373]
Generating valid sharing links using NOM layers is currently broken. Could relate to recent switching off errors for those layers? 

A data supplier generated this link: https://www.nationalmap.gov.au/renewables/#share=s-1lcwasP8SeyEE3EW
 
The intended view is attached:
![NOM intended share view](https://user-images.githubusercontent.com/33736687/59911274-6c0f3d80-940b-11e9-9580-c92e45a576f4.jpg)

The actual view is also attached (right extent, but no layers present):
![NOM actual share view](https://user-images.githubusercontent.com/33736687/59911589-2bfc8a80-940c-11e9-96d3-d92ca94a5cc9.jpg)

Other behaviour to note: 

1. When you select a different Proposed Investment display variable on the second picture the dots show up and the scale appears. 
2. When you do the same for the Available Distribution Capacity the scale shows up but no polygons appear.
3. A regular share link with other (non-NOM) layers works fine so appears to be limited to NOM layers, hence wondering if related to recent error setting change: https://www.nationalmap.gov.au/renewables/#share=s-kOKw8TtHUU4kDhKt 
4. Old sharing links created some time ago that reference the exact same layers DO work, so it appears to be something with the **generation** of a valid link (now), rather than the **loading** of the layers! See working old link: https://nationalmap.gov.au/renewables/#share=s-lc2l3DUfwYHHEnON

**Comment by meh9** [comment]
I have confirmed it's not the `showWarnings` setting causing the problem.

**Comment by kring** [comment]
The immediate problem is the presence of the `active` properties in the column styles. For example, this doesn't work:
https://nationalmap.gov.au/renewables/#https://gist.githubusercontent.com/kring/db742cbacc58213a361a6585eae22957/raw/3b41429e512b994b72741468d3bc670569047744/notworking.json

But if we remove all the `"active": false` and `"active": true` properties, it works:
https://nationalmap.gov.au/renewables/#https://gist.githubusercontent.com/kring/ae71fad12e86a6a4662dee5dcd286998/raw/9499dc664db1c6b6b2110e6e44c02851b2b8df99/working.json

The extra field was added in TerriJS/terriajs#3378, but I'm not sure yet why it was needed for chart sharing or what the proper fix might be. @soyarsauce you're probably best place to take the first look.

**Comment by elangham** [comment]
Hi guys, thanks for quick attention to this - I've tried creating new share links (https://nationalmap.gov.au/renewables/#share=s-wokyZx6LEoATFzIN) and this seemed to have the same issue occurring (Mac, Chrome 75.0.3770.100) - is this one fully resolved?

**Comment by kring** [comment]
@elangham it is fixed in the latest TerriaJS, but we haven't yet deployed AREMI to use it. That'll happen ASAP.

**Comment by elangham** [comment]
ahah, gotcha - thanks for clarifying @kring - if someone could shoot me a note when that happens that would be great and I'll let data suppliers know they can share again
