### ISSUE TITLE
ABBA - NSW update 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/aremi-natmap#376]
1. I've just updated our 4 waste layers on the host server. The attribute data, layer legend and metadata have all changed but same URLs. I checked AREMI and cleared my Cache, but layers are appearing 'confused'! Legend and metadata is from the previous layer and map is only loading about half the polygons, and when info checked they are returning the new tabular data. I'm going to republish these layers and hope that this fixes the issue.

2. I want to change the name of the layers as they appear on AREMI, but not the ArcGIS MXD name (which relates to the URL). I assume I can do this without creating a new URL as it is similar to updating the legend and metadata. Please confirm.

Point 1 and 2 I will be doing for all our published layers over the next couple on months.

3. I am aiming to publish two new layers this week not previously on AREMI for the Cropping folder. Are you able to deploy them at this point in the cycle?

**Comment by AnaBelgun** [comment]
I have set up the new MXD for the Cropping > Straw-Hay-Silage Residues, published it to the REST Service and tested it in AREMI. Looks good and all working well. Please upload this when you get a chance and let me know what you think and how it goes.

https://spatial.industry.nsw.gov.au/arcgis/rest/services/Bioenergy_Assessment/Cropping_StrawHaySilageResidues/MapServer

New folder structure for Cropping (folders in orange yet to create MXDs and layers).

If all goes well, we can take down the following URLs and I will delete them from the REST service.
1. https://spatial.industry.nsw.gov.au/arcgis/rest/services/Bioenergy_Assessment/Cropping_All_Straw_Hay_Silage_Residues/MapServer
2. https://spatial.industry.nsw.gov.au/arcgis/rest/services/Bioenergy_Assessment/Cropping_Cereal_Straw_Residues/MapServer
3. https://spatial.industry.nsw.gov.au/arcgis/rest/services/Bioenergy_Assessment/Cropping_Non_Cereal_Straw_Residues/MapServer
4. https://spatial.industry.nsw.gov.au/arcgis/rest/services/Bioenergy_Assessment/Cropping_Soil_Protection_Zones/MapServer

**Comment by AnaBelgun** [comment]
- [ ] Forestry

I have set up three new MXDs for the Forestry layers. These are: Forestry > General, Forestry > Harvest Residues and Forestry > Sawmill Residues, published them to the REST Service and tested them in AREMI. Looks good and all working well. Please upload this when you get a chance and let me know what you think and how it goes.

Forestry > General 
https://spatial.industry.nsw.gov.au/arcgis/rest/services/Bioenergy_Assessment/Forestry_General/MapServer

Forestry > Harvest Residues 
https://spatial.industry.nsw.gov.au/arcgis/rest/services/Bioenergy_Assessment/Forestry_HarvestResidues/MapServer

Forestry > Sawmill Residues 
https://spatial.industry.nsw.gov.au/arcgis/rest/services/Bioenergy_Assessment/Forestry_SawmillResidues/MapServer

New folder structure for Forestry (folders in orange yet to create MXDs and layers).
 

If all goes well, we can take down the following URLs and I will delete them from the REST service.
https://spatial.industry.nsw.gov.au/arcgis/rest/services/Bioenergy_Assessment/Forestry_NSW_Wood_Processing_Facilities/MapServer
https://spatial.industry.nsw.gov.au/arcgis/rest/services/Bioenergy_Assessment/Forestry_Production_Forests/MapServer
https://spatial.industry.nsw.gov.au/arcgis/rest/services/Bioenergy_Assessment/Forestry_Harvest_Residues_Public_Forests_Overview/MapServer
https://spatial.industry.nsw.gov.au/arcgis/rest/services/Bioenergy_Assessment/Forestry_Harvest_Residues_Public_Native_Forests/MapServer
https://spatial.industry.nsw.gov.au/arcgis/rest/services/Bioenergy_Assessment/Forestry_Harvest_Residues_Public_Plantation_Hardwood/MapServer
https://spatial.industry.nsw.gov.au/arcgis/rest/services/Bioenergy_Assessment/Forestry_Harvest_Residues_Public_Plantation_Softwood/MapServer
https://spatial.industry.nsw.gov.au/arcgis/rest/services/Bioenergy_Assessment/Forestry_Sawmill_Residues_Overview/MapServer
https://spatial.industry.nsw.gov.au/arcgis/rest/services/Bioenergy_Assessment/Forestry_Sawmill_Residues_Hardwood_Cypress/MapServer
https://spatial.industry.nsw.gov.au/arcgis/rest/services/Bioenergy_Assessment/Forestry_Sawmill_Residues_Softwood/MapServer

**Comment by AnaBelgun** [comment]
- [ ] livestock

I have set up the new MXD for the Livestock > Manure Residues, published it to the REST Service and tested it in AREMI. Looks good and all working well. Please upload this when you get a chance and let me know what you think and how it goes.

https://spatial.industry.nsw.gov.au/arcgis/rest/services/Bioenergy_Assessment/Livestock_ManureResidues/MapServer

New folder structure for Livestock (folders in orange yet to create MXDs and layers).
 

If all goes well, we can take down the following URLs and I will delete them from the REST service.
https://spatial.industry.nsw.gov.au/arcgis/rest/services/Bioenergy_Assessment/Livestock_All_Manure_Residues/MapServer
https://spatial.industry.nsw.gov.au/arcgis/rest/services/Bioenergy_Assessment/Livestock_Dairy_Manure_Residues/MapServer
https://spatial.industry.nsw.gov.au/arcgis/rest/services/Bioenergy_Assessment/Livestock_Piggery_Manure_Residues/MapServer
https://spatial.industry.nsw.gov.au/arcgis/rest/services/Bioenergy_Assessment/Livestock_Poultry_Manure_Bedding_Residues/MapServer

**Comment by AnaBelgun** [comment]
- [ ] Cropping

Hi Mats,

I have set up two new MXDs/services for Cropping > Cotton Residues and Cropping > Rice Residues, published them to the REST Service and tested them in AREMI. Looks good and all working well. Please upload these with the next release of data for July. They will both sit in their own folder under the Cropping folder as named below. At the moment they each only contain one layer, but with the changes we are making, I will add the second layers to these MXDs in the future when they are developed and re-publish as discussed would be possible.

Cropping > Cotton Residues 
https://spatial.industry.nsw.gov.au/arcgis/rest/services/Bioenergy_Assessment/Cropping_CottonResidues/MapServer

Cropping > Rice Residues 
https://spatial.industry.nsw.gov.au/arcgis/rest/services/Bioenergy_Assessment/Cropping_RiceResidues/MapServer

**Comment by AnaBelgun** [comment]
- [ ] Horticulture - Nut Residues

I have set up a new MXD/service for Horticulture > Nut Residues and published it to the REST Service and tested it in AREMI. Looks good and all working well. Please upload this with the next release of data for July. This is a new folder under New South Wales. At the moment it contains two layers, but with the changes we are making, I will add more layers to this MXD in the future when they are developed and re-publish as discussed would be possible.

Horticulture > Nut Residues
https://spatial.industry.nsw.gov.au/arcgis/rest/services/Bioenergy_Assessment/Horticulture_NutResidues/MapServer

**Comment by soyarsauce** [comment]
https://www.nationalmap.gov.au/renewables/#clean&proxy/_60s/http://static.aremi.data61.io/init/aremi-2019-07-29.json

**Comment by AnaBelgun** [comment]
- [ ] Waste

I have set up the new MXD for the Waste > Organic Solid Waste, published it to the REST Service and tested it in AREMI. Looks good and all working well. Please upload this when you get a chance and let me know what you think and how it goes.

https://spatial.industry.nsw.gov.au/arcgis/rest/services/Bioenergy_Assessment/Waste_OrganicSolidWaste/MapServer

New folder structure for Waste (folders in orange yet to create MXDs and layers).
 

If all goes well, we can take down the following URLs and I will delete them from the REST service.
https://spatial.industry.nsw.gov.au/arcgis/rest/services/Bioenergy_Assessment/Waste_CandD_Organic/MapServer
https://spatial.industry.nsw.gov.au/arcgis/rest/services/Bioenergy_Assessment/Waste_CandI_Organic/MapServer
https://spatial.industry.nsw.gov.au/arcgis/rest/services/Bioenergy_Assessment/Waste_MSW_CandI_CandD_Organic/MapServer
https://spatial.industry.nsw.gov.au/arcgis/rest/services/Bioenergy_Assessment/Waste_MSW_Organic/MapServer

**Comment by AnaBelgun** [comment]
Additional to fix:

- [ ] under Cropping - remove one of the 2 "residues" words 
![image](https://user-images.githubusercontent.com/18452161/62021206-73471980-b209-11e9-8bd9-2570bb2c3cec.png)

- [ ] under Cropping - remove the Hay and Silage residues sub-folder (this data is now contained in the Straw-Hay-Silage folder)
![image](https://user-images.githubusercontent.com/18452161/62021246-a4274e80-b209-11e9-8f26-986c8632fb1d.png)

- [ ] Update Waste folder

- [ ] There is a problem with the attribute data in the NSW Almond Shells-Hulls (SA4) layer, it's all out of order in the Feature Information window.  NSW team will republish this layer and that should fix it.

**Comment by soyarsauce** [comment]
Addressed first 3, pending republished-service for feature info ordering
https://www.nationalmap.gov.au/renewables/#clean&proxy/_60s/http://static.aremi.data61.io/init/aremi-2019-07-29-75dcb8a7-a1ef-4a6d-8668-3a85cfacc6d6.json

**Comment by AnaBelgun** [comment]
@soyarsauce to handover this to next RelMan
