### ISSUE TITLE
ABBA - update WA data 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/aremi-natmap#390]
Currently there is an inconsistency in how your data layers are “registered with” AREMI
This inconsistency prevents the ABBA analytics code from seeing that there is a CKAN service (where the tags are implemented) hosting the file.
For example, the Cereal Straw layer is listed as a plain csv 
![cereal straw](https://user-images.githubusercontent.com/18452161/64304823-b8acf280-cfd0-11e9-8de1-08ac17e333e4.png)

whereas an example like any of the horticulture layers is listed as a ckan-resource csv
 
![Horticulture](https://user-images.githubusercontent.com/18452161/64304829-bd71a680-cfd0-11e9-994a-c8625d31eb0d.png)

I checked whether that example could be “registered with” AREMI exactly the same way as the Forestry, Horticulture or Dairy layers I have been testing with, and it can.
Cereal straw could have:
datasetId: “cereal-straw-residues”
url: “https://catalogue.data.wa.gov.au”
type: “ckan-resource”
csvResourceFormat: “CSV”

The Cereal Straw, Oil Mallee stems, Grape marc and Seaweed Wrack layers are the only ones that have this inconsistency and can’t have their tags read.

**Comment by AnaBelgun** [comment]
@na9da this is again related to the analytics functionality to be included in AREMI
it depends on States data and the WA inconsistency breaks it

**Comment by na9da** [comment]
I have published the catalog changes.

Quick check: https://www.nationalmap.gov.au/renewables/#share=s-2f6HdXmBXKPgMHTx

**Comment by AnaBelgun** [comment]
@na9da thank you.

When checking the above https://www.nationalmap.gov.au/renewables/#share=s-2f6HdXmBXKPgMHTx

For the oil mallee and cropping data, when you load the data and click on the polygon, it doesn’t display the full data but shows the curated data. You have to click the Show Raw Data tab to display the information you want. Might be good to get rid of that or have the displayed data in the curated data as total biomass/total residues. 

Note: specifically for AREMI data we have created curated templates of feature info, because sometimes it displays too many rows. 
In this case, we might need to revert the template to a default view of all raws/columns

**Comment by na9da** [comment]
Have removed the feature info templating for Oil Mallee item.
