### ISSUE TITLE
Data info overlays not displaying properly

### ISSUE THREAD

**Issue by elangham** [TerriaJS/aremi-natmap#391]
Timeslider and "Expand" chart only appear when text size is changed (clicking _CMD +_) - seems to behave differently after it appears initially when you shrink text back down again. When cancelled the chart feature remains grey
3 screenshots attached of issue/s:
-Timeslider not initially visible until text size change.jpg
-Expand chart not initially visible until text size change.jpg
-Expand chart cancelled.jpg

![1  Timeslider not initially visible until text size change](https://user-images.githubusercontent.com/33736687/64349332-a772de80-cfee-11e9-90c1-e5fbf44c5420.jpg)
![2  Expand chart not initially visible until text size change](https://user-images.githubusercontent.com/33736687/64349331-a772de80-cfee-11e9-86dd-8d67ecc53f6c.jpg)
![3  Expand chart cancelled](https://user-images.githubusercontent.com/33736687/64349330-a6da4800-cfee-11e9-92bd-a3a159bf6512.jpg)

Using: Mac OSX 10.14.6, Chrome 76.0.3809.132
Share URL of dataset being viewed: https://nationalmap.gov.au/renewables/#share=s-b7t9oVvtrgwt1O0L

**Comment by rowanwins** [comment]
Think this was resolved by a number of bug fixes of charts published recently, no longer getting any blank charts.
