### ISSUE TITLE
ABBA - WA group page

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/aremi-natmap#394]
Add description for the WA Group/State page https://drive.google.com/a/csiro.it/file/d/19yod1pb1ORMfWYus7KeslJMhxJpVePVg/view?usp=drive_open

**Comment by rowanwins** [comment]
Is that for this page @AnaBelgun  ?
Renewable Energy -> BioEnergy -> Western Australia 

https://nationalmap.gov.au/renewables/#share=s-wLkI0hNVResjMP0T
