### ISSUE TITLE
ABBA - update group page

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/aremi-natmap#395]
On the ABBA group page, update SA contact details to: 

Department for Energy & Mining
Mary Lewitzka 
Mary.Lewitzka@sa.gov.au

**Comment by rowanwins** [comment]
Where is this page @AnaBelgun ?

**Comment by rowanwins** [comment]
Renewable Energy -> BioEnergy

https://nationalmap.gov.au/renewables/#share=s-9PRfg6VLXyQeYRkA
