### ISSUE TITLE
AREMI - Nov 2019 release

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/aremi-natmap#401]
- [x] finalise the inclusion of ABBA analytics as per tickets and comments in Aug release: https://github.com/TerriaJS/aremi-natmap/issues/382
- https://github.com/TerriaJS/cesium/pull/49
- https://github.com/TerriaJS/terriajs/pull/3609#discussion_r307593537
- https://github.com/TerriaJS/terriajs/pull/3135
![image](https://user-images.githubusercontent.com/18452161/69522990-db8ae980-0fb6-11ea-80cc-6d1498bf9c89.png)

- [x] region mapping fix https://github.com/TerriaJS/aremi-natmap/issues/402

**Comment by rowanwins** [comment]
region mapping done
