### ISSUE TITLE
Replace population density with new services 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/aremi-natmap#426]
Here are the links to the NEXIS Residential Dwelling Density service:

https://services.ga.gov.au/gis/services/NEXIS_Residential_Dwelling_Density/MapServer/WMSServer
https://services.ga.gov.au/gis/services/NEXIS_Residential_Dwelling_Density/MapServer/WCSServer
http://services.ga.gov.au/gis/rest/services/NEXIS_Residential_Dwelling_Density/MapServer

**Comment by rowanwins** [comment]
@AnaBelgun I've looked at this. The trouble so far is the legends (see screen grab below)

Basically there are 4 layers which automatically turn on and off as you zoom closer. At the moment we show all 4 legends at once.

We could add the 4 layers as seperate lines items to the catalog but then the layer is only visible for a certain zoom range which is also annoying...

![Screen_2020_08_07](https://user-images.githubusercontent.com/6735870/89600018-5aedee00-d8a4-11ea-9715-e58a6e20bddb.jpg)

No easy answer sorry

**Comment by AnaBelgun** [comment]
ok, let's leave for now and I'll give this feedback to Steve from GA.

**Comment by AnaBelgun** [comment]
Feedback: 
Our services show the legends for each layers which has, this helps with online requests for layers and printing. However, if you make a basic mapserver legend request (see below) you could translate that json into a single image or html response. I don't think there is an easy answer, it was not designed to combine legend images (I think).

http://services.ga.gov.au/gis/rest/services/NEXIS_Residential_Dwelling_Density/MapServer/legend?f=pjson

http://services.ga.gov.au/gis/rest/services/NEXIS_Residential_Dwelling_Density/MapServer/legend

**Comment by rowanwins** [comment]
I think I'll just hide the legend for the timebeing. In mobx we can perhaps work on scale-dependent legend rendering

**Comment by rowanwins** [comment]
Done in #432
