### ISSUE TITLE
WA Electricity infrastructure - data not available - user prompted for login

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/aremi-natmap#429]
When trying to access the WA electricity layers, the users are prompted for login details, which wasn't the case before: 

![image](https://user-images.githubusercontent.com/18452161/88135843-54684100-cc2b-11ea-832b-8c82c6bbd0cd.png)

When implemented initially, the WA layers required a special configuration set up which permitted the custodian to know the user accessed the data via AREMI. The arrangement was similar to SLIP data on NationalMap. A free account was set up for AREMI users to access the data without being prompted for individual logins (and therefore for them to set up separate accounts). 

https://github.com/TerriaJS/aremi-natmap/issues/177

**Comment by rowanwins** [comment]
This is resolved by 
https://github.com/NICTA/aremi-cloud/pull/19

We discovered a bug with proxyauth handling for deployments
