### ISSUE TITLE
NOM Polygon Rebuild

### ISSUE THREAD

**Issue by elangham** [TerriaJS/aremi-natmap#431]
The final NOM dataset is ready to be prepared for review and shipping to GA. The final files are here:
1.	Geojson: https://network-opportunity-maps.s3-ap-southeast-2.amazonaws.com/constraints/surge/available_capacity.geojson
2.	CSVs
a.	https://network-opportunity-maps.s3-ap-southeast-2.amazonaws.com/constraints/surge/available_capacity_timeseries.csv
b.	https://network-opportunity-maps.s3-ap-southeast-2.amazonaws.com/constraints/surge/deferral_values_timeseries.csv
c.	https://network-opportunity-maps.s3-ap-southeast-2.amazonaws.com/constraints/surge/peak_day.csv
d.	https://network-opportunity-maps.s3-ap-southeast-2.amazonaws.com/constraints/surge/proposed_investment.csv

The test site ([HERE](http://nom-regions-tester.terria.io/#clean&https://gist.githubusercontent.com/elangham/5966c96a04f1a52a677e339a13a74717/raw/c4fcdcde8a2d8b23bc5b9464eb92965ffbdea760/nom-regions-review.json)) Steve built has these loaded up. There are a few things we need to adjust at the same time on the protype for release though:

1. The metadata is attached (NOM Layer Info v17.docx) with a couple of minor definitional adjustments in track changes.
2. We need to ensure that the legends have the right years: the proposed investment legend for “investment year” should run from 2020-2029 (it’s currently 2019-2028)
3. In past we’ve left layer errors set to “off” so you don’t have to process the additional filtering script so please do that again.
4. The default ADV layer start year should be 2027.
5. We’d like to slightly edit the colours on the ADV layer to the following: "colorMap": "rgba(255,255,255,1.0)-rgba(255,255,35,1.0)-rgba(242,198,95,1.0)-rgba(222,112,68,1.0)-rgba(203,40,42,1.0)-rgba(154,31,75,1.0)-rgba(101,31,124,1.0)" – we’ve checked this on our test site.

Ultimately we want to keep the same location as the current public site for the CSVs (in the /published folder) but can’t switch them over directly without breaking things. For this purpose we created a /published-initial folder so we could manage versions then later switch them over to /published, so I’ll use that unless any alternative ideas. 
 
Thanks!
Ed

**Comment by rowanwins** [comment]
This has mostly been done in 
https://github.com/TerriaJS/aremi-natmap/pull/432

@elangham can you email me the metadata doc

**Comment by rowanwins** [comment]
Done in #432
