### ISSUE TITLE
AREMI - Decommissioning 31 Jan 2021

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/aremi-natmap#434]
- [ ] transfer of AREMI datasets on NationalMap (mobx version) - https://github.com/TerriaJS/aremi-natmap/issues/437

- [x] send letter to custodians and collaborators 28 Sep 2020

- [ ] start tweeting after welcome modal is released on v7 AREMI 

- [x] welcome modal on AREMI to inform users - https://github.com/terriajs/aremi-natmap/issues/444

**Comment by AnaBelgun** [comment]
Check catalogue items against NatMap

**Comment by nf-s** [comment]
Nick to look at EV maps

**Comment by AnaBelgun** [comment]
Superseded by https://github.com/TerriaJS/aremi-natmap/issues/437

**Comment by AnaBelgun** [comment]
GA will decommission AREMI on 31 Jan 2021 afternoon.
