### ISSUE TITLE
AREMI - some data services- not available 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/aremi-natmap#436]
1) Pumped Hydro data sets are not available 
Data service hosted and maintained by Terria: https://gis.aremi.data61.io/anu/wms  

https://nationalmap.gov.au/renewables/#share=s-jF0JifEGIqcibua7 

Go to: 
- Renewables
- Hydro
- Storage
- ANU Stores Worlwide 
- any layer from the group
![image](https://user-images.githubusercontent.com/18452161/97098751-b75aef80-16d4-11eb-8f7f-45f5e5b1ad34.png)

2) Wind - Wasp Lib Files (this might be different than ANU Pumped Hydro - TBC) 
Services here: https://gis.aremi.data61.io/dnvgl/wms 
Error: 
![image](https://user-images.githubusercontent.com/18452161/97099181-31da3e00-16da-11eb-8123-f548ac290515.png)

![image](https://user-images.githubusercontent.com/18452161/97099155-c001f480-16d9-11eb-8ddd-aab29bb24afc.png)

**Comment by AnaBelgun** [comment]
GA and users have prompted us the service is not available.

**Comment by soyarsauce** [comment]
@ana to test

**Comment by AnaBelgun** [comment]
Data available now

WaspLIB 
![image](https://user-images.githubusercontent.com/18452161/97257127-1baeb800-1869-11eb-8edf-3771ed59a7b8.png)

Pumped Hydro
![image](https://user-images.githubusercontent.com/18452161/97257153-34b76900-1869-11eb-9db5-9e62abe2ff3d.png)
