### ISSUE TITLE
AREMI - NatMap v8 - connection to token for WA SLIP services

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/aremi-natmap#438]
In current v7 based AREMI, the WA electricity data is available via a Token. This ticket is to remind developers we need the same token implementation in v8. 
See related tickets about initial implementation and subsequent issues: 
- https://github.com/TerriaJS/aremi-natmap/issues/177 
- https://github.com/TerriaJS/aremi-natmap/issues/429

**Comment by nf-s** [comment]
This is already done through `proxyAuth` for `services.slip.wa.gov.au`
