### ISSUE TITLE
AREMI - NatMap v8 - NoM / ISF data migration 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/aremi-natmap#439]
Currently the Network Opportunities Market data from ISF is available in AREMI (v7) using the following: 
1) Region mapping - to use the geometries / zone substastions or other
2) CSVs (mapped to those geometries) - to show some data 
3) Vector data - Outputs of forecasting modelling which could not fit into the CSVs; tabular 

- the CSVs are merged with regions and when you click on the regions, the user gets the vector data to create the charts 
- currently AREMI v7 uses classes of elements; CSS templates / custom sheets which get applied to the templated feature info
- v8 Terria allows to pull data from a different/separate url in the feature info panel 

This ticket is to develop the v8 capabilities for the ISF data to be migrated to NationalMap. To investigate and work on: 
- handling the custom sheets / CSS
- handling the vector data (under 3) to work with region mapping and CSVs

**Comment by AnaBelgun** [comment]
Step 1 - investigation of migration plan - sprint #64 - @steve9164 
Step 2 - break down into 2/3 tickets to start work in sprint #65

**Comment by AnaBelgun** [comment]
Important note from ABBA team: 
Is the "Boundaries/Boundaries used and hosted by ABS" catalogue section in AREMI going to get transferred across to NationalMap as well?
Would you be able to include that in discussions with NationalMap owners if you are not already?

**Comment by steve9164** [comment]
Custom CSS is complicated in our managed map platform. Since NationalMap will continue to be hosted by GA I will re-implement the custom CSS for ISF when we're ready to deploy NationalMap 2.0.

ISF data works in Natmap v2.0 Beta, and feature info will be partially fixed (apart from styles) in TerriaJS/terriajs#5206.

**Comment by AnaBelgun** [comment]
- [ ] feature info template doesn't work in v8

**Comment by nf-s** [comment]
`Peak Day Available Capacity` chart is broken 

![image](https://user-images.githubusercontent.com/6187649/108653359-50cace80-751a-11eb-82de-155d775f255a.png)

**Comment by nf-s** [comment]
Fixed in https://github.com/TerriaJS/terriajs/pull/5234 - I will split up the PR later

**Comment by AnaBelgun** [comment]
included in the SDMX pr -

**Comment by nf-s** [comment]
Fixed here - https://github.com/TerriaJS/terriajs/pull/5315

**Comment by nf-s** [comment]
![image](https://user-images.githubusercontent.com/6187649/115710329-90e0ed00-a3b5-11eb-878a-886e52322e05.png)

Fixed

**Comment by nf-s** [comment]
Can this be closed @AnaBelgun ?
