### ISSUE TITLE
AREMI - EV Traffic volumes - API - v8 migration

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/aremi-natmap#440]
- Handle NSW Traffic API used for Electric Vehicle data group: https://api.transport.nsw.gov.au
1) Average daily traffic volume
2) Average hourly weekday traffic volume

**Comment by soyarsauce** [comment]
Can start this sprint but feeding into the aremi->NM catalaog transfer.

The EV work that Rowan has worked on, seems ok to transfer but need to port the live traffic api volumes. (version 8 / mobx)

Sprint 65 onward

**Comment by nf-s** [comment]
Please assign to @nf-s - I don't have repo permissions to do so.

**Comment by nf-s** [comment]
I have converted the `NswTrafficVolumeCatalogItem` and `NswTrafficHourlyVolumeCatalogItem` to `CsvCatalogItem`. In the process I had to add a few properties to the `catalog-converter` - https://github.com/TerriaJS/catalog-converter/pull/33

I will post v8 catalog JSON with a test link soon

**Comment by nf-s** [comment]
V8 Catalog JSON is finished!
https://gist.github.com/nf-s/1c0db642314fc2ce76753d5bb9ad083c

**Comment by nf-s** [comment]
[ ] - PR which makes Display Variable selctor more pretty - https://github.com/TerriaJS/terriajs/pull/5135

**Comment by nf-s** [comment]
I can't post test link due to NSW API auth credentials

**Comment by nf-s** [comment]
Closing because converted to v8 catalog JSON https://gist.github.com/nf-s/1c0db642314fc2ce76753d5bb9ad083c
