### ISSUE TITLE
AREMI v7 - Jan 2021 release announcement decommissioning

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/aremi-natmap#444]
AREMI needs to be released on v7 to announce the decommissioning of the platform and migration of data to NationalMap 2.0 

Draft text: 

Dear users
As ongoing funding to support maintenance and development has not been identified, the AREMI platform will be decommissioned on 31st of January 2021 with all the relevant datasets being migrated to the [Australian NationalMap ](https://nationalmap.gov.au/). While efforts are made to limit the disruption to users and data custodians, please expect some data or functionalities' discrepancies. Please let us know your feedback by emailing info@terria.io. Thank you for your support!

**Comment by steve9164** [comment]
AREMI code updated in #449. Waiting on @peterhassall to guide a release due to complexity in releasing AREMI.

**Comment by AnaBelgun** [comment]
With GA atm

**Comment by AnaBelgun** [comment]
![image](https://user-images.githubusercontent.com/18452161/106245300-5d803d80-6260-11eb-99ec-5e3eb9423b50.png)
