### ISSUE TITLE
AREMI - AEMO data support in v8

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/aremi-natmap#446]
AEMO data (Current power generation) https://www.nationalmap.gov.au/renewables/#share=s-a9AyUeCdUTbvcFPE needs to be supported in v8 to enable transfer to NationalMap v8.

![image](https://user-images.githubusercontent.com/18452161/104141074-ed249000-5408-11eb-864e-ddfbdd2cc742.png)

**Comment by AnaBelgun** [comment]
This ticket/bug is linked to it: TerriaJS/terriajs#4768

**Comment by nf-s** [comment]
- [ ]  PR to add `terriajs` support for power generation CSV's `timeColumn: null` - https://github.com/TerriaJS/terriajs/pull/5018/

AREMI Power generation test URL http://ci.terria.io/nullable-time-column/#clean&https://gist.githubusercontent.com/nf-s/9ff1422d9528c16a9e71403ec720558a/raw/fe86f1c9bf2dd4053148475dd1361fc7e205ec22/aremi-elec-infra.json
