### ISSUE TITLE
Http data doesn't load over https

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/aremi-natmap#56]
Some browsers default to https://nationalmap.gov.au/renewables/ and then cannot load data - eg. _chart data_, which refers to an http endpoint.  Found by @steve9164 and @legostormtroopr.

> Mixed Content: The page at 'https://nationalmap.gov.au/renewables/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint. This request has been blocked; the content must be served over HTTPS.

**Comment by steve9164** [comment]
This is a larger problem with https. You can't add any data that is served over http to the map (like the Irish lighthouses: http://atlas.marine.ie/arcgis/rest/services/TransportNetworks/MapServer/4?f=pjson).

**Comment by kring** [comment]
@steve9164 TerriaJS is smart enough to use the proxy for requests to HTTP sites from an HTTPS origin.  But your atlas.marine.ie example doesn't do that because that host is not in the proxy whitelist.  Or perhaps TerriaJS isn't set up to use the proxy to request chart data at all?

**Comment by RacingTadpole** [comment]
Interesting... the original issue was for http://services.aremi.nationalmap.gov.au/aemo/v4/duidcsv/NYNGAN1?offset=1D

**Comment by kring** [comment]
Sounds like the chart data loading isn't using `proxyCatalogItemUrl` then?

**Comment by steve9164** [comment]
What is the fix for this? To add services.aremi to the whitelist and not support (and without descriptive error) adding your own hosted data to https Terria maps?

**Comment by kring** [comment]
`*.gov.au` is already in the whitelist.  I think as long as the code that is loading the chart data uses `proxyCatalogItemUrl` or `CorsProxy.getURLProxyIfNecessary` it should all work fine.

**Comment by RacingTadpole** [comment]
Ahh... yes, @kring is right - check out https://github.com/TerriaJS/terriajs/blob/master/lib/ReactViews/Custom/Chart/Chart.jsx#L85 - it just uses the supplied url directly.

**Comment by RacingTadpole** [comment]
I'll open this as a terria issue and close this one.

**Comment by RacingTadpole** [comment]
Actually I'll reopen it and leave this one as an issue for the lighthouse data :-)

**Comment by RacingTadpole** [comment]
Oh, I now realise the Irish lighthouse data was your own added data... I assume we don't want to add that to our whitelist! So, closing again...
