### ISSUE TITLE
Make sure we point to release NEII viewer

### ISSUE THREAD

**Issue by axman6** [TerriaJS/aremi-natmap#57]
See  TerriaJS/nationalmap#363

**Comment by RacingTadpole** [comment]
Do you merge from nationalmap, terriamap, or do your own thing?

**Comment by axman6** [comment]
National Map, thought we don't share any of the catalog, so we'll need to manually fix that.

**Comment by axman6** [comment]
@meh9 I think you already did this?

**Comment by meh9** [comment]
Yeah I think we got it in one of the merges.
