### ISSUE TITLE
Add Vic green waste and organics recovery facilities data

### ISSUE THREAD

**Issue by axman6** [TerriaJS/aremi-natmap#58]
Email from Kelly "FW: Victorian organic waste and resource recovery infrastructure list.xlsx"

**Comment by AnaBelgun** [comment]
Kelly needs to: 
- update lat long information
- replace text in cells with no value, with space/blank cells
- create a WMS based on the updated CSV

Kelly emailed on 22 Dec 16.

**Comment by axman6** [comment]
WMS isn't needed, the CSV is fine.

**Comment by meh9** [comment]
Any update on this?

**Comment by AnaBelgun** [comment]
VIC team has confirmed to close this ticket. New data file and catalogue structure has been provided on 7 Jun 17.
