### ISSUE TITLE
Add public NGERS data - Designated Generating Facilities

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/aremi-natmap#59]
CER has asked for the Designated Generating Facilities (all power stations in Australia, not just the NEM) to be added to AREMI. Data is public; it has not location information. 
[Copy of Designated generation facilities report 2014-15.xlsx](https://github.com/TerriaJS/aremi-natmap/files/668006/Copy.of.Designated.generation.facilities.report.2014-15.xlsx)
 
James Tyrrell contacted on 21 Dec 16 to provide the location.

**Comment by axman6** [comment]
@meh9 Did you start on this?

**Comment by meh9** [comment]
Yes, and then I got distracted. Will resume.

**Comment by meh9** [comment]
@axman6 is taking this over.

**Comment by axman6** [comment]
All done!
