### ISSUE TITLE
Add NSW bioenergy assessment data 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/aremi-natmap#64]
New South Wales (main heading)
Forestry (group heading)
https://spatial.industry.nsw.gov.au/arcgis/rest/services/Bioenergy_Assessment/Forestry_Harvest_Residues_Native_Hardwoods/MapServer
https://spatial.industry.nsw.gov.au/arcgis/rest/services/Bioenergy_Assessment/Forestry_Harvest_Residues_Planted_Softwoods/MapServer
https://spatial.industry.nsw.gov.au/arcgis/rest/services/Bioenergy_Assessment/Forestry_NSW_Wood_Processing_Facilities/MapServer
https://spatial.industry.nsw.gov.au/arcgis/rest/services/Bioenergy_Assessment/NSW_State_Forests/MapServer
Cropping (group heading)
https://spatial.industry.nsw.gov.au/arcgis/rest/services/Bioenergy_Assessment/Cropping_All_Straw_Residues/MapServer
https://spatial.industry.nsw.gov.au/arcgis/rest/services/Bioenergy_Assessment/Cropping_Cereal_Straw_Residues/MapServer
https://spatial.industry.nsw.gov.au/arcgis/rest/services/Bioenergy_Assessment/Cropping_Non_Cereal_Straw_Residues/MapServer
https://spatial.industry.nsw.gov.au/arcgis/rest/services/Bioenergy_Assessment/Cropping_Soil_Protection_Zones/MapServer

Also, please continue to attach the statement below to the Forestry group heading, as the metadata doesn't have this information (it will be remedied in the future when more layers are completed for the Forestry group). 

Note: This statement is contained within the Cropping layers so no need to add to this group heading.
Licensing, Terms & Use Conditions
These datasets have been made available for information purposes only. No claim is made as to the accuracy or authenticity of the data. The NSW Government and this department (Department of Industry - Lands) does not accept any liability to any person for the information or advice (or the use of such information or advice) which has been provided in this dataset.

**Comment by axman6** [comment]
Finished by @meh9
