### ISSUE TITLE
Make NGERS colours more distinct for low values

### ISSUE THREAD

**Issue by axman6** [TerriaJS/aremi-natmap#66]
CER brought up the issue of colours not doing a good job of representing the differences between low values in the NGERS designated generation facilities, maybe a log scale may help, but we'll need to platy with a few options.

**Comment by meh9** [comment]
Did you get anywhere with this?

**Comment by axman6** [comment]
Will look into faking a logarithmic scale.

```
 "colorMap": "rgba(81,16,43,1.0)-rgba(165,0,38,1.0)-rgba(215,48,39,1.0)-rgba(244,109,67,1.0)-rgba(253,174,97,1.0)-rgba(254,224,144,1.0)-rgba(255,255,191,1.0)-rgba(224,243,248,1.0)-rgba(171,217,233,1.0)-rgba(116,165,209,1.0)-rgba(69,107,200,1.0)-rgba(49,54,201,1.0)",
 "colorBins": [0,1,3,5,10,30,50,100,300,500,1000,3000],
 "minDisplayValue": 0,
 "maxDisplayValue": 3000
```

**Comment by axman6** [comment]
For the longer term, I've made a ticket to get logarithmic scales in TerriaJS, but this will need to be done too: https://github.com/TerriaJS/terriajs/issues/2601
