### ISSUE TITLE
Single inverted comma appearing as incorrect symbol

### ISSUE THREAD

**Issue by MakeupArtist** [TerriaJS/aremi-natmap#67]
The NationalMaps code base is having trouble displaying single inverted commas. Please check AREMI for this same problem. The single inverted comma is being displayed a 'question mark' inside a diamond.

**Comment by meh9** [comment]
Sorry for taking so long to get back to you on this.

I'm afraid I would need some more information about where to see this problem in order to reproduce and fix it. Can you tell me where you experienced the problem?

**Comment by axman6** [comment]
No response from reporter. This appears to be a text encoding issue, the question mark in diamond symbol is used when a unicode stream could not decode a character, this is usually because Windows has been used.
