### ISSUE TITLE
Shorten URL checkbox appears to have no affect

### ISSUE THREAD

**Issue by MakeupArtist** [TerriaJS/aremi-natmap#72]
Shorten URL checkbox appears to have no affect on the text in the links in the SHARE button at the top right of the application.

**Comment by meh9** [comment]
It should have an effect, unfortunately the part of the URL that is shortened is usually off the side of the screen.

This is something we are aware of that we want to improve in the future.

**Comment by axman6** [comment]
@meh9 can you expand on what we should do here?
