### ISSUE TITLE
Full Screen Button is actually Full Window Button

### ISSUE THREAD

**Issue by MakeupArtist** [TerriaJS/aremi-natmap#74]
The full screen button does not actually use the whole window for the map and then set the browser into full screen mode. It only sets the map to fill the whole browser window. If the browser window is taking up on a tiny part of the computer screen, this situation is not affected by selecting this option. Therefore this option should be 'Go to Full WIndow / Exit Full Window' rather than Full Screen / Exit Full Screen.

**Comment by meh9** [comment]
We now call this "Hide/Show workbench".
