### ISSUE TITLE
Capitalisation inconsistency

### ISSUE THREAD

**Issue by MakeupArtist** [TerriaJS/aremi-natmap#75]
On left hand side under search box, Message says 'Add Data' but button says 'Add data'. D in 'data' in button is not capitalised.

**Comment by a-stacey** [comment]
This was fixed in https://github.com/TerriaJS/terriajs/commit/9be53d539260ce72de9249b4cbbf4b14ed427a7b - TerriaJS: 9be53d539260ce72de9249b4cbbf4b14ed427a7b.

![screenshot from 2017-07-24 15-58-43](https://user-images.githubusercontent.com/4453477/28509996-1c9aebf2-7089-11e7-8518-79b61c370b4b.png)
