### ISSUE TITLE
Add QLD biogas data under Bioenergy

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/aremi-natmap#81]
Hi Alex,
 
Here is the link http://biogas.nceastg.usq.edu.au/data/biogas.csv. Lidya has tested the format in http://nationalmap.gov.au/renewables/ and it is working and has modified it so that each time a new record is added to the survey page, the list in this csv file gets updated too.

**Comment by meh9** [comment]
> Regarding where in the catalogue the data can be placed – you’re right it is not state specific so the best place would be under Bioenergy category and make a new link labelled ‘Biogas Facilities’.

**Comment by AnaBelgun** [comment]
No metadata - data description, custodian text, licensing and terms of use received yet (20 Apr 17)

**Comment by meh9** [comment]
Added as a preview layer for now.
