### ISSUE TITLE
Update GA layers

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/aremi-natmap#86]
The following services:
·         NM_Hydrography_and_Marine
·         NM_Hydrography_and_Marine_Lines
·         NM_Hydrography_and_Marine_Points
·         NM_Hydrography_and_Marine_Polygons
 
Have been replaced by the following due to incorrect spelling in the service:
·         NM_Hydrology_and_Marine
·         NM_Hydrology_and_Marine_Lines
·         NM_Hydrology_and_Marine_Points
·         NM_Hydrology_and_Marine_Polygons

- the Land Tenure service in AREMI is still pointing to the old service. This was actually due for decommission today (12 April 17) to be extended for another month, but that will be all the extension time allowed.
 - to switch Cadastre Parcels over, as it will also be going into the decom process soon.

**Comment by meh9** [comment]
AREMI doesn't use the NM_Hydrography* layers.

**Comment by AnaBelgun** [comment]
The new names did not affect the hydrology_marine layers on NationalMap; they all  work as of 19 April (in the catalogue they can be found under the Dynamic Hydrology and Marine Layer and the Individual Hydrology and Marine Layers).

**Comment by meh9** [comment]
Land Tenure and Cadastre Parcel services have been switched to the new _WM versions.
