### ISSUE TITLE
To add NSW Bioenergy layers

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/aremi-natmap#87]
They are all cropping layers so could you please upload my layers using the URLs below into the AREMI Cropping folder.

I have 2 new URLs (3 new layers) to upload and 1 to remove. I have already stopped the map service for the layer that will be removed.
New layers (and folder names):
Cropping > All Straw, Hay & Silage Residues
https://spatial.industry.nsw.gov.au/arcgis/rest/services/Bioenergy_Assessment/Cropping_All_Straw_Hay_Silage_Residues/MapServer (contains 1 layer)

Cropping > Hay and Silage Residues
https://spatial.industry.nsw.gov.au/arcgis/rest/services/Bioenergy_Assessment/Cropping_Hay_Silage_Residues/MapServer (contains 2 layers)
Remove layer (map service already stopped):
Cropping > All Straw Residues
https://spatial.industry.nsw.gov.au/arcgis/rest/services/Bioenergy_Assessment/Cropping_All_Straw_Residues/MapServer (contains 1 layer)
Unchanged:
Cropping > Cereal Straw Residues (contains 2 layers)
Cropping > Non Cereal Straw Residues (contains 2 layers)
Cropping > Soil Protection Zones (contains 1 layer)

Please follow the layout you have already created for the Cropping datasets (as it looks good and is clear to understand) and use the folder names above for the new layers. In total there will be 8 cropping layers on AREMI.

Also, I was able to load and view my URLs through the live AREMI platform (http://nationalmap.gov.au/renewables/) but not through the prototype platform (http://prototype.aremi.d61.io/renewables/). The error message returned is below.

**Comment by meh9** [comment]
Done in 3f5b7e5b72f4f8de5fcf933dccc9f46c9a0732a9.
