### ISSUE TITLE
Add SA Bioenergy layers

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/aremi-natmap#88]
Add the following URLs for the SA Bioenergy. 
-  not able to add these directly to AREMI but they sometimes work in the prototype – which is crashing out a bit when you try to zoom in.
 
AGRICULTURE SA4
SA4_CERAL_STRAW
http://location.sa.gov.au/arcgis3/rest/services/AREMI/Cereal_Straw/MapServer/0
SA4_NON_CERAL_STRAW
http://location.sa.gov.au/arcgis3/rest/services/AREMI/Non_Cereal_Straw/MapServer/0
SA4_HAY_SILAGE
http://location.sa.gov.au/arcgis3/rest/services/AREMI/Hay_and_Silage/MapServer/0
 
HORTICULTURE
SA4_FRUIT_NUTS
http://location.sa.gov.au/arcgis3/rest/services/AREMI/Fruit_Nuts/MapServer/0
SA4_VEGETABLES
http://location.sa.gov.au/arcgis3/rest/services/AREMI/Vegetables/MapServer/0
 
SIMULATED RESIDUAL STRAW – Reduced Rainfall Scenarios
Simulated Residual Straw – Average Rainfall (1900 – 2009)
http://location.sa.gov.au/arcgis3/rest/services/AREMI/Simulated_Residual_Straw_Average_Rainfall/MapServer/0
Simulated Residual Straw – 5% Reduced Rainfall
http://location.sa.gov.au/arcgis3/rest/services/AREMI/Simulated_Residual_Straw_5pc_Reduced_Rainfall/MapServer
Simulated Residual Straw – 10% Reduced Rainfall
http://location.sa.gov.au/arcgis3/rest/services/AREMI/Simulated_Residual_Straw_10pc_Reduced_Rainfall/MapServer/0
Simulated Residual Straw – 20% Reduced Rainfall
http://location.sa.gov.au/arcgis3/rest/services/AREMI/Simulated_Residual_Straw_20pc_Reduced_Rainfall/MapServer/0
 
 
- interested in removing the kml’s used previously

**Comment by meh9** [comment]
The new layers are now up, but marked as prototype due to problems with the server performance.

**Comment by meh9** [comment]
No longer marked as prototype, but still waiting on changes from Mary.

**Comment by meh9** [comment]
Mary emailed her layers to be added.

**Comment by meh9** [comment]
Fixed in 57641872c2525d2ebc51eb1674d736b6e1c79a7c.
