### ISSUE TITLE
AREMI 2017-04-24 pre-release test - URL for legend just opens a new session

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/aremi-natmap#91]
Layer Topography/Aerial-Satellite Imagery/Queensland

URL to open the legend in a new tab just starts a new session - no legend!

![aremi-2017-04-24-issue-1](https://cloud.githubusercontent.com/assets/22827786/25605129/13cc0908-2f4c-11e7-9e0c-27404595de5b.jpg)

**Comment by meh9** [comment]
Have removed the legend link.
