### ISSUE TITLE
AREMI 2017-04-24 pre-release test - Missing legend and wrong feature information?

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/aremi-natmap#92]
Layer: Topography/Areial-Satellite Imagery/New South Wales

Issues:
- Missing legend
- Feature information showing block/parcel boundary attributes. Not sure if this is expected. Expected imagery information or values.
![aremi-2017-04-24-issue-2](https://cloud.githubusercontent.com/assets/22827786/25605250/e384f34e-2f4c-11e7-91da-c43ed348583c.jpg)

**Comment by meh9** [comment]
Legends are not helpful for RGB satellite imagery as there are no distinct features. I have disabled feature information for this layer since it was not returning useful values.
