### ISSUE TITLE
AREMI 2017-04-24 pre-release test - Missing legend and feature information

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/aremi-natmap#93]
Layer: Topography/Elevation/Land slope in percent

Issues:
- No legend
- No feature information - shows 'No data is available here - try another location.'
- User unable to figure out the data being displayed
![aremi-2017-04-24-issue-3](https://cloud.githubusercontent.com/assets/22827786/25605452/361d1eb4-2f4e-11e7-99e0-3679fb88fad9.jpg)

**Comment by meh9** [comment]
The data custodian, Geoscience Australia, does not provide a legend or feature info data for this layer.
