### ISSUE TITLE
AREMI 2017-04-24 pre-release test - Labelling missing data

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/aremi-natmap#94]
Layer:
Topography/Elevation/LIDAR 25m DEM

Issue:
- Feature Information - Labelling 'NoData metres' for missing values!

![aremi-2017-04-24-issue-4](https://cloud.githubusercontent.com/assets/22827786/25605532/d29cb06a-2f4e-11e7-8346-ae5748aa3f3b.jpg)

**Comment by meh9** [comment]
Fixed.
