### ISSUE TITLE
Add Lat/Lon to all templates for raster layers, or as necessary

### ISSUE THREAD

**Issue by meh9** [TerriaJS/aremi-natmap#97]
Kinda related to TerriaJS/terriajs#2510.

We have rasters like Solar Satellite, Average Wind etc where when you click you actually have no info in the feature info about exactly where you clicked. Lets add that to all those rasters.

**Comment by a-stacey** [comment]
I can't assign (...presumably because I'm not a member), but just a note to indicate that I'm looking into this.

**Comment by rowanwins** [comment]
Lat lon info shown on click

![LatLon](https://user-images.githubusercontent.com/6735870/70407826-e99e3700-1a99-11ea-945e-c261062fe8e6.png)
