### ISSUE TITLE
Native Title Determination data - error message

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/aremi-natmap#99]
Error message when accessing Native Title Determination dataset: 
![image](https://cloud.githubusercontent.com/assets/18452161/26434676/62431da2-414d-11e7-9ea4-85eca7093224.png)

**Comment by AnaBelgun** [comment]
Ana to investigate with Native Title Tribunal Northern Territory

**Comment by AnaBelgun** [comment]
Please fix and send the prototype url to Steven Rodgers (user needs it for Conference about Indigenous native titles).

**Comment by axman6** [comment]
Fixed
